
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Footer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Footer
 * 
 */
export type FooterModel = runtime.Types.Result.DefaultSelection<Prisma.$FooterPayload>

export type AggregateFooter = {
  _count: FooterCountAggregateOutputType | null
  _min: FooterMinAggregateOutputType | null
  _max: FooterMaxAggregateOutputType | null
}

export type FooterMinAggregateOutputType = {
  id: string | null
  logo: string | null
  description: string | null
  phone: string | null
  email: string | null
  address: string | null
  copyright: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FooterMaxAggregateOutputType = {
  id: string | null
  logo: string | null
  description: string | null
  phone: string | null
  email: string | null
  address: string | null
  copyright: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FooterCountAggregateOutputType = {
  id: number
  logo: number
  description: number
  phone: number
  email: number
  address: number
  copyright: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FooterMinAggregateInputType = {
  id?: true
  logo?: true
  description?: true
  phone?: true
  email?: true
  address?: true
  copyright?: true
  createdAt?: true
  updatedAt?: true
}

export type FooterMaxAggregateInputType = {
  id?: true
  logo?: true
  description?: true
  phone?: true
  email?: true
  address?: true
  copyright?: true
  createdAt?: true
  updatedAt?: true
}

export type FooterCountAggregateInputType = {
  id?: true
  logo?: true
  description?: true
  phone?: true
  email?: true
  address?: true
  copyright?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FooterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Footer to aggregate.
   */
  where?: Prisma.FooterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Footers to fetch.
   */
  orderBy?: Prisma.FooterOrderByWithRelationInput | Prisma.FooterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FooterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Footers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Footers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Footers
  **/
  _count?: true | FooterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FooterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FooterMaxAggregateInputType
}

export type GetFooterAggregateType<T extends FooterAggregateArgs> = {
      [P in keyof T & keyof AggregateFooter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFooter[P]>
    : Prisma.GetScalarType<T[P], AggregateFooter[P]>
}




export type FooterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterWhereInput
  orderBy?: Prisma.FooterOrderByWithAggregationInput | Prisma.FooterOrderByWithAggregationInput[]
  by: Prisma.FooterScalarFieldEnum[] | Prisma.FooterScalarFieldEnum
  having?: Prisma.FooterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FooterCountAggregateInputType | true
  _min?: FooterMinAggregateInputType
  _max?: FooterMaxAggregateInputType
}

export type FooterGroupByOutputType = {
  id: string
  logo: string | null
  description: string | null
  phone: string | null
  email: string | null
  address: string | null
  copyright: string | null
  createdAt: Date
  updatedAt: Date
  _count: FooterCountAggregateOutputType | null
  _min: FooterMinAggregateOutputType | null
  _max: FooterMaxAggregateOutputType | null
}

export type GetFooterGroupByPayload<T extends FooterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FooterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FooterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FooterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FooterGroupByOutputType[P]>
      }
    >
  >



export type FooterWhereInput = {
  AND?: Prisma.FooterWhereInput | Prisma.FooterWhereInput[]
  OR?: Prisma.FooterWhereInput[]
  NOT?: Prisma.FooterWhereInput | Prisma.FooterWhereInput[]
  id?: Prisma.StringFilter<"Footer"> | string
  logo?: Prisma.StringNullableFilter<"Footer"> | string | null
  description?: Prisma.StringNullableFilter<"Footer"> | string | null
  phone?: Prisma.StringNullableFilter<"Footer"> | string | null
  email?: Prisma.StringNullableFilter<"Footer"> | string | null
  address?: Prisma.StringNullableFilter<"Footer"> | string | null
  copyright?: Prisma.StringNullableFilter<"Footer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Footer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Footer"> | Date | string
  socialLinks?: Prisma.FooterSocialListRelationFilter
  sections?: Prisma.FooterSectionListRelationFilter
}

export type FooterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  logo?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  copyright?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  socialLinks?: Prisma.FooterSocialOrderByRelationAggregateInput
  sections?: Prisma.FooterSectionOrderByRelationAggregateInput
}

export type FooterWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FooterWhereInput | Prisma.FooterWhereInput[]
  OR?: Prisma.FooterWhereInput[]
  NOT?: Prisma.FooterWhereInput | Prisma.FooterWhereInput[]
  logo?: Prisma.StringNullableFilter<"Footer"> | string | null
  description?: Prisma.StringNullableFilter<"Footer"> | string | null
  phone?: Prisma.StringNullableFilter<"Footer"> | string | null
  email?: Prisma.StringNullableFilter<"Footer"> | string | null
  address?: Prisma.StringNullableFilter<"Footer"> | string | null
  copyright?: Prisma.StringNullableFilter<"Footer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Footer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Footer"> | Date | string
  socialLinks?: Prisma.FooterSocialListRelationFilter
  sections?: Prisma.FooterSectionListRelationFilter
}, "id">

export type FooterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  logo?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  copyright?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FooterCountOrderByAggregateInput
  _max?: Prisma.FooterMaxOrderByAggregateInput
  _min?: Prisma.FooterMinOrderByAggregateInput
}

export type FooterScalarWhereWithAggregatesInput = {
  AND?: Prisma.FooterScalarWhereWithAggregatesInput | Prisma.FooterScalarWhereWithAggregatesInput[]
  OR?: Prisma.FooterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FooterScalarWhereWithAggregatesInput | Prisma.FooterScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Footer"> | string
  logo?: Prisma.StringNullableWithAggregatesFilter<"Footer"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Footer"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"Footer"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"Footer"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"Footer"> | string | null
  copyright?: Prisma.StringNullableWithAggregatesFilter<"Footer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Footer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Footer"> | Date | string
}

export type FooterCreateInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  socialLinks?: Prisma.FooterSocialCreateNestedManyWithoutFooterInput
  sections?: Prisma.FooterSectionCreateNestedManyWithoutFooterInput
}

export type FooterUncheckedCreateInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  socialLinks?: Prisma.FooterSocialUncheckedCreateNestedManyWithoutFooterInput
  sections?: Prisma.FooterSectionUncheckedCreateNestedManyWithoutFooterInput
}

export type FooterUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  socialLinks?: Prisma.FooterSocialUpdateManyWithoutFooterNestedInput
  sections?: Prisma.FooterSectionUpdateManyWithoutFooterNestedInput
}

export type FooterUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  socialLinks?: Prisma.FooterSocialUncheckedUpdateManyWithoutFooterNestedInput
  sections?: Prisma.FooterSectionUncheckedUpdateManyWithoutFooterNestedInput
}

export type FooterCreateManyInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FooterUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FooterUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FooterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  copyright?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FooterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  copyright?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FooterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  logo?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  copyright?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FooterScalarRelationFilter = {
  is?: Prisma.FooterWhereInput
  isNot?: Prisma.FooterWhereInput
}

export type FooterCreateNestedOneWithoutSocialLinksInput = {
  create?: Prisma.XOR<Prisma.FooterCreateWithoutSocialLinksInput, Prisma.FooterUncheckedCreateWithoutSocialLinksInput>
  connectOrCreate?: Prisma.FooterCreateOrConnectWithoutSocialLinksInput
  connect?: Prisma.FooterWhereUniqueInput
}

export type FooterUpdateOneRequiredWithoutSocialLinksNestedInput = {
  create?: Prisma.XOR<Prisma.FooterCreateWithoutSocialLinksInput, Prisma.FooterUncheckedCreateWithoutSocialLinksInput>
  connectOrCreate?: Prisma.FooterCreateOrConnectWithoutSocialLinksInput
  upsert?: Prisma.FooterUpsertWithoutSocialLinksInput
  connect?: Prisma.FooterWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FooterUpdateToOneWithWhereWithoutSocialLinksInput, Prisma.FooterUpdateWithoutSocialLinksInput>, Prisma.FooterUncheckedUpdateWithoutSocialLinksInput>
}

export type FooterCreateNestedOneWithoutSectionsInput = {
  create?: Prisma.XOR<Prisma.FooterCreateWithoutSectionsInput, Prisma.FooterUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.FooterCreateOrConnectWithoutSectionsInput
  connect?: Prisma.FooterWhereUniqueInput
}

export type FooterUpdateOneRequiredWithoutSectionsNestedInput = {
  create?: Prisma.XOR<Prisma.FooterCreateWithoutSectionsInput, Prisma.FooterUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.FooterCreateOrConnectWithoutSectionsInput
  upsert?: Prisma.FooterUpsertWithoutSectionsInput
  connect?: Prisma.FooterWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FooterUpdateToOneWithWhereWithoutSectionsInput, Prisma.FooterUpdateWithoutSectionsInput>, Prisma.FooterUncheckedUpdateWithoutSectionsInput>
}

export type FooterCreateWithoutSocialLinksInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.FooterSectionCreateNestedManyWithoutFooterInput
}

export type FooterUncheckedCreateWithoutSocialLinksInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sections?: Prisma.FooterSectionUncheckedCreateNestedManyWithoutFooterInput
}

export type FooterCreateOrConnectWithoutSocialLinksInput = {
  where: Prisma.FooterWhereUniqueInput
  create: Prisma.XOR<Prisma.FooterCreateWithoutSocialLinksInput, Prisma.FooterUncheckedCreateWithoutSocialLinksInput>
}

export type FooterUpsertWithoutSocialLinksInput = {
  update: Prisma.XOR<Prisma.FooterUpdateWithoutSocialLinksInput, Prisma.FooterUncheckedUpdateWithoutSocialLinksInput>
  create: Prisma.XOR<Prisma.FooterCreateWithoutSocialLinksInput, Prisma.FooterUncheckedCreateWithoutSocialLinksInput>
  where?: Prisma.FooterWhereInput
}

export type FooterUpdateToOneWithWhereWithoutSocialLinksInput = {
  where?: Prisma.FooterWhereInput
  data: Prisma.XOR<Prisma.FooterUpdateWithoutSocialLinksInput, Prisma.FooterUncheckedUpdateWithoutSocialLinksInput>
}

export type FooterUpdateWithoutSocialLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.FooterSectionUpdateManyWithoutFooterNestedInput
}

export type FooterUncheckedUpdateWithoutSocialLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.FooterSectionUncheckedUpdateManyWithoutFooterNestedInput
}

export type FooterCreateWithoutSectionsInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  socialLinks?: Prisma.FooterSocialCreateNestedManyWithoutFooterInput
}

export type FooterUncheckedCreateWithoutSectionsInput = {
  id?: string
  logo?: string | null
  description?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  copyright?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  socialLinks?: Prisma.FooterSocialUncheckedCreateNestedManyWithoutFooterInput
}

export type FooterCreateOrConnectWithoutSectionsInput = {
  where: Prisma.FooterWhereUniqueInput
  create: Prisma.XOR<Prisma.FooterCreateWithoutSectionsInput, Prisma.FooterUncheckedCreateWithoutSectionsInput>
}

export type FooterUpsertWithoutSectionsInput = {
  update: Prisma.XOR<Prisma.FooterUpdateWithoutSectionsInput, Prisma.FooterUncheckedUpdateWithoutSectionsInput>
  create: Prisma.XOR<Prisma.FooterCreateWithoutSectionsInput, Prisma.FooterUncheckedCreateWithoutSectionsInput>
  where?: Prisma.FooterWhereInput
}

export type FooterUpdateToOneWithWhereWithoutSectionsInput = {
  where?: Prisma.FooterWhereInput
  data: Prisma.XOR<Prisma.FooterUpdateWithoutSectionsInput, Prisma.FooterUncheckedUpdateWithoutSectionsInput>
}

export type FooterUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  socialLinks?: Prisma.FooterSocialUpdateManyWithoutFooterNestedInput
}

export type FooterUncheckedUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  logo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  copyright?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  socialLinks?: Prisma.FooterSocialUncheckedUpdateManyWithoutFooterNestedInput
}


/**
 * Count Type FooterCountOutputType
 */

export type FooterCountOutputType = {
  socialLinks: number
  sections: number
}

export type FooterCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  socialLinks?: boolean | FooterCountOutputTypeCountSocialLinksArgs
  sections?: boolean | FooterCountOutputTypeCountSectionsArgs
}

/**
 * FooterCountOutputType without action
 */
export type FooterCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterCountOutputType
   */
  select?: Prisma.FooterCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FooterCountOutputType without action
 */
export type FooterCountOutputTypeCountSocialLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterSocialWhereInput
}

/**
 * FooterCountOutputType without action
 */
export type FooterCountOutputTypeCountSectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterSectionWhereInput
}


export type FooterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logo?: boolean
  description?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  copyright?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  socialLinks?: boolean | Prisma.Footer$socialLinksArgs<ExtArgs>
  sections?: boolean | Prisma.Footer$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.FooterCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["footer"]>

export type FooterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logo?: boolean
  description?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  copyright?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["footer"]>

export type FooterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  logo?: boolean
  description?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  copyright?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["footer"]>

export type FooterSelectScalar = {
  id?: boolean
  logo?: boolean
  description?: boolean
  phone?: boolean
  email?: boolean
  address?: boolean
  copyright?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FooterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "logo" | "description" | "phone" | "email" | "address" | "copyright" | "createdAt" | "updatedAt", ExtArgs["result"]["footer"]>
export type FooterInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  socialLinks?: boolean | Prisma.Footer$socialLinksArgs<ExtArgs>
  sections?: boolean | Prisma.Footer$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.FooterCountOutputTypeDefaultArgs<ExtArgs>
}
export type FooterIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FooterIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FooterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Footer"
  objects: {
    socialLinks: Prisma.$FooterSocialPayload<ExtArgs>[]
    sections: Prisma.$FooterSectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    logo: string | null
    description: string | null
    phone: string | null
    email: string | null
    address: string | null
    copyright: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["footer"]>
  composites: {}
}

export type FooterGetPayload<S extends boolean | null | undefined | FooterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FooterPayload, S>

export type FooterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FooterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FooterCountAggregateInputType | true
  }

export interface FooterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Footer'], meta: { name: 'Footer' } }
  /**
   * Find zero or one Footer that matches the filter.
   * @param {FooterFindUniqueArgs} args - Arguments to find a Footer
   * @example
   * // Get one Footer
   * const footer = await prisma.footer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FooterFindUniqueArgs>(args: Prisma.SelectSubset<T, FooterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Footer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FooterFindUniqueOrThrowArgs} args - Arguments to find a Footer
   * @example
   * // Get one Footer
   * const footer = await prisma.footer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FooterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FooterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Footer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterFindFirstArgs} args - Arguments to find a Footer
   * @example
   * // Get one Footer
   * const footer = await prisma.footer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FooterFindFirstArgs>(args?: Prisma.SelectSubset<T, FooterFindFirstArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Footer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterFindFirstOrThrowArgs} args - Arguments to find a Footer
   * @example
   * // Get one Footer
   * const footer = await prisma.footer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FooterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FooterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Footers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Footers
   * const footers = await prisma.footer.findMany()
   * 
   * // Get first 10 Footers
   * const footers = await prisma.footer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const footerWithIdOnly = await prisma.footer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FooterFindManyArgs>(args?: Prisma.SelectSubset<T, FooterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Footer.
   * @param {FooterCreateArgs} args - Arguments to create a Footer.
   * @example
   * // Create one Footer
   * const Footer = await prisma.footer.create({
   *   data: {
   *     // ... data to create a Footer
   *   }
   * })
   * 
   */
  create<T extends FooterCreateArgs>(args: Prisma.SelectSubset<T, FooterCreateArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Footers.
   * @param {FooterCreateManyArgs} args - Arguments to create many Footers.
   * @example
   * // Create many Footers
   * const footer = await prisma.footer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FooterCreateManyArgs>(args?: Prisma.SelectSubset<T, FooterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Footers and returns the data saved in the database.
   * @param {FooterCreateManyAndReturnArgs} args - Arguments to create many Footers.
   * @example
   * // Create many Footers
   * const footer = await prisma.footer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Footers and only return the `id`
   * const footerWithIdOnly = await prisma.footer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FooterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FooterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Footer.
   * @param {FooterDeleteArgs} args - Arguments to delete one Footer.
   * @example
   * // Delete one Footer
   * const Footer = await prisma.footer.delete({
   *   where: {
   *     // ... filter to delete one Footer
   *   }
   * })
   * 
   */
  delete<T extends FooterDeleteArgs>(args: Prisma.SelectSubset<T, FooterDeleteArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Footer.
   * @param {FooterUpdateArgs} args - Arguments to update one Footer.
   * @example
   * // Update one Footer
   * const footer = await prisma.footer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FooterUpdateArgs>(args: Prisma.SelectSubset<T, FooterUpdateArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Footers.
   * @param {FooterDeleteManyArgs} args - Arguments to filter Footers to delete.
   * @example
   * // Delete a few Footers
   * const { count } = await prisma.footer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FooterDeleteManyArgs>(args?: Prisma.SelectSubset<T, FooterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Footers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Footers
   * const footer = await prisma.footer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FooterUpdateManyArgs>(args: Prisma.SelectSubset<T, FooterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Footers and returns the data updated in the database.
   * @param {FooterUpdateManyAndReturnArgs} args - Arguments to update many Footers.
   * @example
   * // Update many Footers
   * const footer = await prisma.footer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Footers and only return the `id`
   * const footerWithIdOnly = await prisma.footer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FooterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FooterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Footer.
   * @param {FooterUpsertArgs} args - Arguments to update or create a Footer.
   * @example
   * // Update or create a Footer
   * const footer = await prisma.footer.upsert({
   *   create: {
   *     // ... data to create a Footer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Footer we want to update
   *   }
   * })
   */
  upsert<T extends FooterUpsertArgs>(args: Prisma.SelectSubset<T, FooterUpsertArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Footers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterCountArgs} args - Arguments to filter Footers to count.
   * @example
   * // Count the number of Footers
   * const count = await prisma.footer.count({
   *   where: {
   *     // ... the filter for the Footers we want to count
   *   }
   * })
  **/
  count<T extends FooterCountArgs>(
    args?: Prisma.Subset<T, FooterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FooterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Footer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FooterAggregateArgs>(args: Prisma.Subset<T, FooterAggregateArgs>): Prisma.PrismaPromise<GetFooterAggregateType<T>>

  /**
   * Group by Footer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FooterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FooterGroupByArgs['orderBy'] }
      : { orderBy?: FooterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FooterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFooterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Footer model
 */
readonly fields: FooterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Footer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FooterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  socialLinks<T extends Prisma.Footer$socialLinksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Footer$socialLinksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sections<T extends Prisma.Footer$sectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Footer$sectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Footer model
 */
export interface FooterFieldRefs {
  readonly id: Prisma.FieldRef<"Footer", 'String'>
  readonly logo: Prisma.FieldRef<"Footer", 'String'>
  readonly description: Prisma.FieldRef<"Footer", 'String'>
  readonly phone: Prisma.FieldRef<"Footer", 'String'>
  readonly email: Prisma.FieldRef<"Footer", 'String'>
  readonly address: Prisma.FieldRef<"Footer", 'String'>
  readonly copyright: Prisma.FieldRef<"Footer", 'String'>
  readonly createdAt: Prisma.FieldRef<"Footer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Footer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Footer findUnique
 */
export type FooterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * Filter, which Footer to fetch.
   */
  where: Prisma.FooterWhereUniqueInput
}

/**
 * Footer findUniqueOrThrow
 */
export type FooterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * Filter, which Footer to fetch.
   */
  where: Prisma.FooterWhereUniqueInput
}

/**
 * Footer findFirst
 */
export type FooterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * Filter, which Footer to fetch.
   */
  where?: Prisma.FooterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Footers to fetch.
   */
  orderBy?: Prisma.FooterOrderByWithRelationInput | Prisma.FooterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Footers.
   */
  cursor?: Prisma.FooterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Footers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Footers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Footers.
   */
  distinct?: Prisma.FooterScalarFieldEnum | Prisma.FooterScalarFieldEnum[]
}

/**
 * Footer findFirstOrThrow
 */
export type FooterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * Filter, which Footer to fetch.
   */
  where?: Prisma.FooterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Footers to fetch.
   */
  orderBy?: Prisma.FooterOrderByWithRelationInput | Prisma.FooterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Footers.
   */
  cursor?: Prisma.FooterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Footers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Footers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Footers.
   */
  distinct?: Prisma.FooterScalarFieldEnum | Prisma.FooterScalarFieldEnum[]
}

/**
 * Footer findMany
 */
export type FooterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * Filter, which Footers to fetch.
   */
  where?: Prisma.FooterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Footers to fetch.
   */
  orderBy?: Prisma.FooterOrderByWithRelationInput | Prisma.FooterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Footers.
   */
  cursor?: Prisma.FooterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Footers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Footers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Footers.
   */
  distinct?: Prisma.FooterScalarFieldEnum | Prisma.FooterScalarFieldEnum[]
}

/**
 * Footer create
 */
export type FooterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * The data needed to create a Footer.
   */
  data: Prisma.XOR<Prisma.FooterCreateInput, Prisma.FooterUncheckedCreateInput>
}

/**
 * Footer createMany
 */
export type FooterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Footers.
   */
  data: Prisma.FooterCreateManyInput | Prisma.FooterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Footer createManyAndReturn
 */
export type FooterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * The data used to create many Footers.
   */
  data: Prisma.FooterCreateManyInput | Prisma.FooterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Footer update
 */
export type FooterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * The data needed to update a Footer.
   */
  data: Prisma.XOR<Prisma.FooterUpdateInput, Prisma.FooterUncheckedUpdateInput>
  /**
   * Choose, which Footer to update.
   */
  where: Prisma.FooterWhereUniqueInput
}

/**
 * Footer updateMany
 */
export type FooterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Footers.
   */
  data: Prisma.XOR<Prisma.FooterUpdateManyMutationInput, Prisma.FooterUncheckedUpdateManyInput>
  /**
   * Filter which Footers to update
   */
  where?: Prisma.FooterWhereInput
  /**
   * Limit how many Footers to update.
   */
  limit?: number
}

/**
 * Footer updateManyAndReturn
 */
export type FooterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * The data used to update Footers.
   */
  data: Prisma.XOR<Prisma.FooterUpdateManyMutationInput, Prisma.FooterUncheckedUpdateManyInput>
  /**
   * Filter which Footers to update
   */
  where?: Prisma.FooterWhereInput
  /**
   * Limit how many Footers to update.
   */
  limit?: number
}

/**
 * Footer upsert
 */
export type FooterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * The filter to search for the Footer to update in case it exists.
   */
  where: Prisma.FooterWhereUniqueInput
  /**
   * In case the Footer found by the `where` argument doesn't exist, create a new Footer with this data.
   */
  create: Prisma.XOR<Prisma.FooterCreateInput, Prisma.FooterUncheckedCreateInput>
  /**
   * In case the Footer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FooterUpdateInput, Prisma.FooterUncheckedUpdateInput>
}

/**
 * Footer delete
 */
export type FooterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
  /**
   * Filter which Footer to delete.
   */
  where: Prisma.FooterWhereUniqueInput
}

/**
 * Footer deleteMany
 */
export type FooterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Footers to delete
   */
  where?: Prisma.FooterWhereInput
  /**
   * Limit how many Footers to delete.
   */
  limit?: number
}

/**
 * Footer.socialLinks
 */
export type Footer$socialLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  where?: Prisma.FooterSocialWhereInput
  orderBy?: Prisma.FooterSocialOrderByWithRelationInput | Prisma.FooterSocialOrderByWithRelationInput[]
  cursor?: Prisma.FooterSocialWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FooterSocialScalarFieldEnum | Prisma.FooterSocialScalarFieldEnum[]
}

/**
 * Footer.sections
 */
export type Footer$sectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSection
   */
  select?: Prisma.FooterSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSection
   */
  omit?: Prisma.FooterSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSectionInclude<ExtArgs> | null
  where?: Prisma.FooterSectionWhereInput
  orderBy?: Prisma.FooterSectionOrderByWithRelationInput | Prisma.FooterSectionOrderByWithRelationInput[]
  cursor?: Prisma.FooterSectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FooterSectionScalarFieldEnum | Prisma.FooterSectionScalarFieldEnum[]
}

/**
 * Footer without action
 */
export type FooterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Footer
   */
  select?: Prisma.FooterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Footer
   */
  omit?: Prisma.FooterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterInclude<ExtArgs> | null
}
