
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Client: 'Client',
  Banner: 'Banner',
  Brand: 'Brand',
  Category: 'Category',
  CompanyInfo: 'CompanyInfo',
  Footer: 'Footer',
  FooterSocial: 'FooterSocial',
  FooterSection: 'FooterSection',
  FooterLink: 'FooterLink',
  Product: 'Product',
  ProductImage: 'ProductImage',
  Ingredient: 'Ingredient',
  ProductUsage: 'ProductUsage',
  ProductBenefit: 'ProductBenefit',
  ProductSEO: 'ProductSEO',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "client" | "banner" | "brand" | "category" | "companyInfo" | "footer" | "footerSocial" | "footerSection" | "footerLink" | "product" | "productImage" | "ingredient" | "productUsage" | "productBenefit" | "productSEO" | "user"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Client: {
      payload: Prisma.$ClientPayload<ExtArgs>
      fields: Prisma.ClientFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ClientFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ClientFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>
        }
        findFirst: {
          args: Prisma.ClientFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ClientFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>
        }
        findMany: {
          args: Prisma.ClientFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>[]
        }
        create: {
          args: Prisma.ClientCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>
        }
        createMany: {
          args: Prisma.ClientCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ClientCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>[]
        }
        delete: {
          args: Prisma.ClientDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>
        }
        update: {
          args: Prisma.ClientUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>
        }
        deleteMany: {
          args: Prisma.ClientDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ClientUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ClientUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>[]
        }
        upsert: {
          args: Prisma.ClientUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientPayload>
        }
        aggregate: {
          args: Prisma.ClientAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateClient>
        }
        groupBy: {
          args: Prisma.ClientGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClientGroupByOutputType>[]
        }
        count: {
          args: Prisma.ClientCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClientCountAggregateOutputType> | number
        }
      }
    }
    Banner: {
      payload: Prisma.$BannerPayload<ExtArgs>
      fields: Prisma.BannerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BannerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BannerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>
        }
        findFirst: {
          args: Prisma.BannerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BannerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>
        }
        findMany: {
          args: Prisma.BannerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>[]
        }
        create: {
          args: Prisma.BannerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>
        }
        createMany: {
          args: Prisma.BannerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BannerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>[]
        }
        delete: {
          args: Prisma.BannerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>
        }
        update: {
          args: Prisma.BannerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>
        }
        deleteMany: {
          args: Prisma.BannerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BannerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BannerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>[]
        }
        upsert: {
          args: Prisma.BannerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BannerPayload>
        }
        aggregate: {
          args: Prisma.BannerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBanner>
        }
        groupBy: {
          args: Prisma.BannerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BannerGroupByOutputType>[]
        }
        count: {
          args: Prisma.BannerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BannerCountAggregateOutputType> | number
        }
      }
    }
    Brand: {
      payload: Prisma.$BrandPayload<ExtArgs>
      fields: Prisma.BrandFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BrandFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BrandFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>
        }
        findFirst: {
          args: Prisma.BrandFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BrandFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>
        }
        findMany: {
          args: Prisma.BrandFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>[]
        }
        create: {
          args: Prisma.BrandCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>
        }
        createMany: {
          args: Prisma.BrandCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BrandCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>[]
        }
        delete: {
          args: Prisma.BrandDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>
        }
        update: {
          args: Prisma.BrandUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>
        }
        deleteMany: {
          args: Prisma.BrandDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BrandUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BrandUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>[]
        }
        upsert: {
          args: Prisma.BrandUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BrandPayload>
        }
        aggregate: {
          args: Prisma.BrandAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBrand>
        }
        groupBy: {
          args: Prisma.BrandGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BrandGroupByOutputType>[]
        }
        count: {
          args: Prisma.BrandCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BrandCountAggregateOutputType> | number
        }
      }
    }
    Category: {
      payload: Prisma.$CategoryPayload<ExtArgs>
      fields: Prisma.CategoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CategoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CategoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>
        }
        findFirst: {
          args: Prisma.CategoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CategoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>
        }
        findMany: {
          args: Prisma.CategoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>[]
        }
        create: {
          args: Prisma.CategoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>
        }
        createMany: {
          args: Prisma.CategoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CategoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>[]
        }
        delete: {
          args: Prisma.CategoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>
        }
        update: {
          args: Prisma.CategoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>
        }
        deleteMany: {
          args: Prisma.CategoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CategoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CategoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>[]
        }
        upsert: {
          args: Prisma.CategoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CategoryPayload>
        }
        aggregate: {
          args: Prisma.CategoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCategory>
        }
        groupBy: {
          args: Prisma.CategoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CategoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.CategoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CategoryCountAggregateOutputType> | number
        }
      }
    }
    CompanyInfo: {
      payload: Prisma.$CompanyInfoPayload<ExtArgs>
      fields: Prisma.CompanyInfoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CompanyInfoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CompanyInfoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>
        }
        findFirst: {
          args: Prisma.CompanyInfoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CompanyInfoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>
        }
        findMany: {
          args: Prisma.CompanyInfoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>[]
        }
        create: {
          args: Prisma.CompanyInfoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>
        }
        createMany: {
          args: Prisma.CompanyInfoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CompanyInfoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>[]
        }
        delete: {
          args: Prisma.CompanyInfoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>
        }
        update: {
          args: Prisma.CompanyInfoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>
        }
        deleteMany: {
          args: Prisma.CompanyInfoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CompanyInfoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CompanyInfoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>[]
        }
        upsert: {
          args: Prisma.CompanyInfoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyInfoPayload>
        }
        aggregate: {
          args: Prisma.CompanyInfoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCompanyInfo>
        }
        groupBy: {
          args: Prisma.CompanyInfoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompanyInfoGroupByOutputType>[]
        }
        count: {
          args: Prisma.CompanyInfoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompanyInfoCountAggregateOutputType> | number
        }
      }
    }
    Footer: {
      payload: Prisma.$FooterPayload<ExtArgs>
      fields: Prisma.FooterFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FooterFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FooterFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>
        }
        findFirst: {
          args: Prisma.FooterFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FooterFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>
        }
        findMany: {
          args: Prisma.FooterFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>[]
        }
        create: {
          args: Prisma.FooterCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>
        }
        createMany: {
          args: Prisma.FooterCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FooterCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>[]
        }
        delete: {
          args: Prisma.FooterDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>
        }
        update: {
          args: Prisma.FooterUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>
        }
        deleteMany: {
          args: Prisma.FooterDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FooterUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FooterUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>[]
        }
        upsert: {
          args: Prisma.FooterUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterPayload>
        }
        aggregate: {
          args: Prisma.FooterAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFooter>
        }
        groupBy: {
          args: Prisma.FooterGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterGroupByOutputType>[]
        }
        count: {
          args: Prisma.FooterCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterCountAggregateOutputType> | number
        }
      }
    }
    FooterSocial: {
      payload: Prisma.$FooterSocialPayload<ExtArgs>
      fields: Prisma.FooterSocialFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FooterSocialFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FooterSocialFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>
        }
        findFirst: {
          args: Prisma.FooterSocialFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FooterSocialFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>
        }
        findMany: {
          args: Prisma.FooterSocialFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>[]
        }
        create: {
          args: Prisma.FooterSocialCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>
        }
        createMany: {
          args: Prisma.FooterSocialCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FooterSocialCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>[]
        }
        delete: {
          args: Prisma.FooterSocialDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>
        }
        update: {
          args: Prisma.FooterSocialUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>
        }
        deleteMany: {
          args: Prisma.FooterSocialDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FooterSocialUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FooterSocialUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>[]
        }
        upsert: {
          args: Prisma.FooterSocialUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSocialPayload>
        }
        aggregate: {
          args: Prisma.FooterSocialAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFooterSocial>
        }
        groupBy: {
          args: Prisma.FooterSocialGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterSocialGroupByOutputType>[]
        }
        count: {
          args: Prisma.FooterSocialCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterSocialCountAggregateOutputType> | number
        }
      }
    }
    FooterSection: {
      payload: Prisma.$FooterSectionPayload<ExtArgs>
      fields: Prisma.FooterSectionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FooterSectionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FooterSectionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>
        }
        findFirst: {
          args: Prisma.FooterSectionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FooterSectionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>
        }
        findMany: {
          args: Prisma.FooterSectionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>[]
        }
        create: {
          args: Prisma.FooterSectionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>
        }
        createMany: {
          args: Prisma.FooterSectionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FooterSectionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>[]
        }
        delete: {
          args: Prisma.FooterSectionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>
        }
        update: {
          args: Prisma.FooterSectionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>
        }
        deleteMany: {
          args: Prisma.FooterSectionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FooterSectionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FooterSectionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>[]
        }
        upsert: {
          args: Prisma.FooterSectionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterSectionPayload>
        }
        aggregate: {
          args: Prisma.FooterSectionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFooterSection>
        }
        groupBy: {
          args: Prisma.FooterSectionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterSectionGroupByOutputType>[]
        }
        count: {
          args: Prisma.FooterSectionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterSectionCountAggregateOutputType> | number
        }
      }
    }
    FooterLink: {
      payload: Prisma.$FooterLinkPayload<ExtArgs>
      fields: Prisma.FooterLinkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FooterLinkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FooterLinkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>
        }
        findFirst: {
          args: Prisma.FooterLinkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FooterLinkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>
        }
        findMany: {
          args: Prisma.FooterLinkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>[]
        }
        create: {
          args: Prisma.FooterLinkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>
        }
        createMany: {
          args: Prisma.FooterLinkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FooterLinkCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>[]
        }
        delete: {
          args: Prisma.FooterLinkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>
        }
        update: {
          args: Prisma.FooterLinkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>
        }
        deleteMany: {
          args: Prisma.FooterLinkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FooterLinkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FooterLinkUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>[]
        }
        upsert: {
          args: Prisma.FooterLinkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FooterLinkPayload>
        }
        aggregate: {
          args: Prisma.FooterLinkAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFooterLink>
        }
        groupBy: {
          args: Prisma.FooterLinkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterLinkGroupByOutputType>[]
        }
        count: {
          args: Prisma.FooterLinkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FooterLinkCountAggregateOutputType> | number
        }
      }
    }
    Product: {
      payload: Prisma.$ProductPayload<ExtArgs>
      fields: Prisma.ProductFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProductFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProductFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>
        }
        findFirst: {
          args: Prisma.ProductFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProductFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>
        }
        findMany: {
          args: Prisma.ProductFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>[]
        }
        create: {
          args: Prisma.ProductCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>
        }
        createMany: {
          args: Prisma.ProductCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProductCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>[]
        }
        delete: {
          args: Prisma.ProductDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>
        }
        update: {
          args: Prisma.ProductUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>
        }
        deleteMany: {
          args: Prisma.ProductDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProductUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProductUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>[]
        }
        upsert: {
          args: Prisma.ProductUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>
        }
        aggregate: {
          args: Prisma.ProductAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProduct>
        }
        groupBy: {
          args: Prisma.ProductGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProductCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductCountAggregateOutputType> | number
        }
      }
    }
    ProductImage: {
      payload: Prisma.$ProductImagePayload<ExtArgs>
      fields: Prisma.ProductImageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProductImageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProductImageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>
        }
        findFirst: {
          args: Prisma.ProductImageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProductImageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>
        }
        findMany: {
          args: Prisma.ProductImageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>[]
        }
        create: {
          args: Prisma.ProductImageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>
        }
        createMany: {
          args: Prisma.ProductImageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProductImageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>[]
        }
        delete: {
          args: Prisma.ProductImageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>
        }
        update: {
          args: Prisma.ProductImageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>
        }
        deleteMany: {
          args: Prisma.ProductImageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProductImageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProductImageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>[]
        }
        upsert: {
          args: Prisma.ProductImageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductImagePayload>
        }
        aggregate: {
          args: Prisma.ProductImageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProductImage>
        }
        groupBy: {
          args: Prisma.ProductImageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductImageGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProductImageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductImageCountAggregateOutputType> | number
        }
      }
    }
    Ingredient: {
      payload: Prisma.$IngredientPayload<ExtArgs>
      fields: Prisma.IngredientFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IngredientFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IngredientFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        findFirst: {
          args: Prisma.IngredientFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IngredientFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        findMany: {
          args: Prisma.IngredientFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>[]
        }
        create: {
          args: Prisma.IngredientCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        createMany: {
          args: Prisma.IngredientCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IngredientCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>[]
        }
        delete: {
          args: Prisma.IngredientDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        update: {
          args: Prisma.IngredientUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        deleteMany: {
          args: Prisma.IngredientDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IngredientUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IngredientUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>[]
        }
        upsert: {
          args: Prisma.IngredientUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IngredientPayload>
        }
        aggregate: {
          args: Prisma.IngredientAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIngredient>
        }
        groupBy: {
          args: Prisma.IngredientGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IngredientGroupByOutputType>[]
        }
        count: {
          args: Prisma.IngredientCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IngredientCountAggregateOutputType> | number
        }
      }
    }
    ProductUsage: {
      payload: Prisma.$ProductUsagePayload<ExtArgs>
      fields: Prisma.ProductUsageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProductUsageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProductUsageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>
        }
        findFirst: {
          args: Prisma.ProductUsageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProductUsageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>
        }
        findMany: {
          args: Prisma.ProductUsageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>[]
        }
        create: {
          args: Prisma.ProductUsageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>
        }
        createMany: {
          args: Prisma.ProductUsageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProductUsageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>[]
        }
        delete: {
          args: Prisma.ProductUsageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>
        }
        update: {
          args: Prisma.ProductUsageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>
        }
        deleteMany: {
          args: Prisma.ProductUsageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProductUsageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProductUsageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>[]
        }
        upsert: {
          args: Prisma.ProductUsageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductUsagePayload>
        }
        aggregate: {
          args: Prisma.ProductUsageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProductUsage>
        }
        groupBy: {
          args: Prisma.ProductUsageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductUsageGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProductUsageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductUsageCountAggregateOutputType> | number
        }
      }
    }
    ProductBenefit: {
      payload: Prisma.$ProductBenefitPayload<ExtArgs>
      fields: Prisma.ProductBenefitFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProductBenefitFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProductBenefitFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>
        }
        findFirst: {
          args: Prisma.ProductBenefitFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProductBenefitFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>
        }
        findMany: {
          args: Prisma.ProductBenefitFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>[]
        }
        create: {
          args: Prisma.ProductBenefitCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>
        }
        createMany: {
          args: Prisma.ProductBenefitCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProductBenefitCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>[]
        }
        delete: {
          args: Prisma.ProductBenefitDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>
        }
        update: {
          args: Prisma.ProductBenefitUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>
        }
        deleteMany: {
          args: Prisma.ProductBenefitDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProductBenefitUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProductBenefitUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>[]
        }
        upsert: {
          args: Prisma.ProductBenefitUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductBenefitPayload>
        }
        aggregate: {
          args: Prisma.ProductBenefitAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProductBenefit>
        }
        groupBy: {
          args: Prisma.ProductBenefitGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductBenefitGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProductBenefitCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductBenefitCountAggregateOutputType> | number
        }
      }
    }
    ProductSEO: {
      payload: Prisma.$ProductSEOPayload<ExtArgs>
      fields: Prisma.ProductSEOFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProductSEOFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProductSEOFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>
        }
        findFirst: {
          args: Prisma.ProductSEOFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProductSEOFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>
        }
        findMany: {
          args: Prisma.ProductSEOFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>[]
        }
        create: {
          args: Prisma.ProductSEOCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>
        }
        createMany: {
          args: Prisma.ProductSEOCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProductSEOCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>[]
        }
        delete: {
          args: Prisma.ProductSEODeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>
        }
        update: {
          args: Prisma.ProductSEOUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>
        }
        deleteMany: {
          args: Prisma.ProductSEODeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProductSEOUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProductSEOUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>[]
        }
        upsert: {
          args: Prisma.ProductSEOUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductSEOPayload>
        }
        aggregate: {
          args: Prisma.ProductSEOAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProductSEO>
        }
        groupBy: {
          args: Prisma.ProductSEOGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductSEOGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProductSEOCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductSEOCountAggregateOutputType> | number
        }
      }
    }
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  segment: 'segment',
  status: 'status',
  avatar: 'avatar',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientScalarFieldEnum = (typeof ClientScalarFieldEnum)[keyof typeof ClientScalarFieldEnum]


export const BannerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  tag: 'tag',
  description: 'description',
  imageType: 'imageType',
  device: 'device',
  imageUrl: 'imageUrl',
  status: 'status',
  isActive: 'isActive',
  clientId: 'clientId',
  categoryId: 'categoryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BannerScalarFieldEnum = (typeof BannerScalarFieldEnum)[keyof typeof BannerScalarFieldEnum]


export const BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  createdAt: 'createdAt'
} as const

export type BrandScalarFieldEnum = (typeof BrandScalarFieldEnum)[keyof typeof BrandScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const CompanyInfoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  address: 'address',
  phone: 'phone',
  email: 'email',
  logoUrl: 'logoUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CompanyInfoScalarFieldEnum = (typeof CompanyInfoScalarFieldEnum)[keyof typeof CompanyInfoScalarFieldEnum]


export const FooterScalarFieldEnum = {
  id: 'id',
  logo: 'logo',
  description: 'description',
  phone: 'phone',
  email: 'email',
  address: 'address',
  copyright: 'copyright',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FooterScalarFieldEnum = (typeof FooterScalarFieldEnum)[keyof typeof FooterScalarFieldEnum]


export const FooterSocialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  url: 'url',
  footerId: 'footerId'
} as const

export type FooterSocialScalarFieldEnum = (typeof FooterSocialScalarFieldEnum)[keyof typeof FooterSocialScalarFieldEnum]


export const FooterSectionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  footerId: 'footerId'
} as const

export type FooterSectionScalarFieldEnum = (typeof FooterSectionScalarFieldEnum)[keyof typeof FooterSectionScalarFieldEnum]


export const FooterLinkScalarFieldEnum = {
  id: 'id',
  label: 'label',
  href: 'href',
  sectionId: 'sectionId'
} as const

export type FooterLinkScalarFieldEnum = (typeof FooterLinkScalarFieldEnum)[keyof typeof FooterLinkScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  shortDescription: 'shortDescription',
  description: 'description',
  price: 'price',
  comparePrice: 'comparePrice',
  stock: 'stock',
  skinType: 'skinType',
  status: 'status',
  categoryId: 'categoryId',
  brandId: 'brandId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductImageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url',
  alt: 'alt',
  isPrimary: 'isPrimary',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt'
} as const

export type ProductImageScalarFieldEnum = (typeof ProductImageScalarFieldEnum)[keyof typeof ProductImageScalarFieldEnum]


export const IngredientScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  percentage: 'percentage'
} as const

export type IngredientScalarFieldEnum = (typeof IngredientScalarFieldEnum)[keyof typeof IngredientScalarFieldEnum]


export const ProductUsageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  stepNumber: 'stepNumber',
  content: 'content'
} as const

export type ProductUsageScalarFieldEnum = (typeof ProductUsageScalarFieldEnum)[keyof typeof ProductUsageScalarFieldEnum]


export const ProductBenefitScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  title: 'title'
} as const

export type ProductBenefitScalarFieldEnum = (typeof ProductBenefitScalarFieldEnum)[keyof typeof ProductBenefitScalarFieldEnum]


export const ProductSEOScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  metaKeyword: 'metaKeyword'
} as const

export type ProductSEOScalarFieldEnum = (typeof ProductSEOScalarFieldEnum)[keyof typeof ProductSEOScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'ProductStatus'
 */
export type EnumProductStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ProductStatus'>
    


/**
 * Reference to a field of type 'ProductStatus[]'
 */
export type ListEnumProductStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ProductStatus[]'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Role[]'
 */
export type ListEnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  client?: Prisma.ClientOmit
  banner?: Prisma.BannerOmit
  brand?: Prisma.BrandOmit
  category?: Prisma.CategoryOmit
  companyInfo?: Prisma.CompanyInfoOmit
  footer?: Prisma.FooterOmit
  footerSocial?: Prisma.FooterSocialOmit
  footerSection?: Prisma.FooterSectionOmit
  footerLink?: Prisma.FooterLinkOmit
  product?: Prisma.ProductOmit
  productImage?: Prisma.ProductImageOmit
  ingredient?: Prisma.IngredientOmit
  productUsage?: Prisma.ProductUsageOmit
  productBenefit?: Prisma.ProductBenefitOmit
  productSEO?: Prisma.ProductSEOOmit
  user?: Prisma.UserOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

