
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Client: 'Client',
  Banner: 'Banner',
  Brand: 'Brand',
  Category: 'Category',
  CompanyInfo: 'CompanyInfo',
  Footer: 'Footer',
  FooterSocial: 'FooterSocial',
  FooterSection: 'FooterSection',
  FooterLink: 'FooterLink',
  Product: 'Product',
  ProductImage: 'ProductImage',
  Ingredient: 'Ingredient',
  ProductUsage: 'ProductUsage',
  ProductBenefit: 'ProductBenefit',
  ProductSEO: 'ProductSEO',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  segment: 'segment',
  status: 'status',
  avatar: 'avatar',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientScalarFieldEnum = (typeof ClientScalarFieldEnum)[keyof typeof ClientScalarFieldEnum]


export const BannerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  tag: 'tag',
  description: 'description',
  imageType: 'imageType',
  device: 'device',
  imageUrl: 'imageUrl',
  status: 'status',
  isActive: 'isActive',
  clientId: 'clientId',
  categoryId: 'categoryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BannerScalarFieldEnum = (typeof BannerScalarFieldEnum)[keyof typeof BannerScalarFieldEnum]


export const BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  createdAt: 'createdAt'
} as const

export type BrandScalarFieldEnum = (typeof BrandScalarFieldEnum)[keyof typeof BrandScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const CompanyInfoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  address: 'address',
  phone: 'phone',
  email: 'email',
  logoUrl: 'logoUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CompanyInfoScalarFieldEnum = (typeof CompanyInfoScalarFieldEnum)[keyof typeof CompanyInfoScalarFieldEnum]


export const FooterScalarFieldEnum = {
  id: 'id',
  logo: 'logo',
  description: 'description',
  phone: 'phone',
  email: 'email',
  address: 'address',
  copyright: 'copyright',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FooterScalarFieldEnum = (typeof FooterScalarFieldEnum)[keyof typeof FooterScalarFieldEnum]


export const FooterSocialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  url: 'url',
  footerId: 'footerId'
} as const

export type FooterSocialScalarFieldEnum = (typeof FooterSocialScalarFieldEnum)[keyof typeof FooterSocialScalarFieldEnum]


export const FooterSectionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  footerId: 'footerId'
} as const

export type FooterSectionScalarFieldEnum = (typeof FooterSectionScalarFieldEnum)[keyof typeof FooterSectionScalarFieldEnum]


export const FooterLinkScalarFieldEnum = {
  id: 'id',
  label: 'label',
  href: 'href',
  sectionId: 'sectionId'
} as const

export type FooterLinkScalarFieldEnum = (typeof FooterLinkScalarFieldEnum)[keyof typeof FooterLinkScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  shortDescription: 'shortDescription',
  description: 'description',
  price: 'price',
  comparePrice: 'comparePrice',
  stock: 'stock',
  skinType: 'skinType',
  status: 'status',
  categoryId: 'categoryId',
  brandId: 'brandId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductImageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url',
  alt: 'alt',
  isPrimary: 'isPrimary',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt'
} as const

export type ProductImageScalarFieldEnum = (typeof ProductImageScalarFieldEnum)[keyof typeof ProductImageScalarFieldEnum]


export const IngredientScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  percentage: 'percentage'
} as const

export type IngredientScalarFieldEnum = (typeof IngredientScalarFieldEnum)[keyof typeof IngredientScalarFieldEnum]


export const ProductUsageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  stepNumber: 'stepNumber',
  content: 'content'
} as const

export type ProductUsageScalarFieldEnum = (typeof ProductUsageScalarFieldEnum)[keyof typeof ProductUsageScalarFieldEnum]


export const ProductBenefitScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  title: 'title'
} as const

export type ProductBenefitScalarFieldEnum = (typeof ProductBenefitScalarFieldEnum)[keyof typeof ProductBenefitScalarFieldEnum]


export const ProductSEOScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  metaKeyword: 'metaKeyword'
} as const

export type ProductSEOScalarFieldEnum = (typeof ProductSEOScalarFieldEnum)[keyof typeof ProductSEOScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

