
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FooterSocial` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FooterSocial
 * 
 */
export type FooterSocialModel = runtime.Types.Result.DefaultSelection<Prisma.$FooterSocialPayload>

export type AggregateFooterSocial = {
  _count: FooterSocialCountAggregateOutputType | null
  _min: FooterSocialMinAggregateOutputType | null
  _max: FooterSocialMaxAggregateOutputType | null
}

export type FooterSocialMinAggregateOutputType = {
  id: string | null
  name: string | null
  icon: string | null
  url: string | null
  footerId: string | null
}

export type FooterSocialMaxAggregateOutputType = {
  id: string | null
  name: string | null
  icon: string | null
  url: string | null
  footerId: string | null
}

export type FooterSocialCountAggregateOutputType = {
  id: number
  name: number
  icon: number
  url: number
  footerId: number
  _all: number
}


export type FooterSocialMinAggregateInputType = {
  id?: true
  name?: true
  icon?: true
  url?: true
  footerId?: true
}

export type FooterSocialMaxAggregateInputType = {
  id?: true
  name?: true
  icon?: true
  url?: true
  footerId?: true
}

export type FooterSocialCountAggregateInputType = {
  id?: true
  name?: true
  icon?: true
  url?: true
  footerId?: true
  _all?: true
}

export type FooterSocialAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterSocial to aggregate.
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocials to fetch.
   */
  orderBy?: Prisma.FooterSocialOrderByWithRelationInput | Prisma.FooterSocialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FooterSocialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FooterSocials
  **/
  _count?: true | FooterSocialCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FooterSocialMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FooterSocialMaxAggregateInputType
}

export type GetFooterSocialAggregateType<T extends FooterSocialAggregateArgs> = {
      [P in keyof T & keyof AggregateFooterSocial]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFooterSocial[P]>
    : Prisma.GetScalarType<T[P], AggregateFooterSocial[P]>
}




export type FooterSocialGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FooterSocialWhereInput
  orderBy?: Prisma.FooterSocialOrderByWithAggregationInput | Prisma.FooterSocialOrderByWithAggregationInput[]
  by: Prisma.FooterSocialScalarFieldEnum[] | Prisma.FooterSocialScalarFieldEnum
  having?: Prisma.FooterSocialScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FooterSocialCountAggregateInputType | true
  _min?: FooterSocialMinAggregateInputType
  _max?: FooterSocialMaxAggregateInputType
}

export type FooterSocialGroupByOutputType = {
  id: string
  name: string
  icon: string | null
  url: string
  footerId: string
  _count: FooterSocialCountAggregateOutputType | null
  _min: FooterSocialMinAggregateOutputType | null
  _max: FooterSocialMaxAggregateOutputType | null
}

export type GetFooterSocialGroupByPayload<T extends FooterSocialGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FooterSocialGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FooterSocialGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FooterSocialGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FooterSocialGroupByOutputType[P]>
      }
    >
  >



export type FooterSocialWhereInput = {
  AND?: Prisma.FooterSocialWhereInput | Prisma.FooterSocialWhereInput[]
  OR?: Prisma.FooterSocialWhereInput[]
  NOT?: Prisma.FooterSocialWhereInput | Prisma.FooterSocialWhereInput[]
  id?: Prisma.StringFilter<"FooterSocial"> | string
  name?: Prisma.StringFilter<"FooterSocial"> | string
  icon?: Prisma.StringNullableFilter<"FooterSocial"> | string | null
  url?: Prisma.StringFilter<"FooterSocial"> | string
  footerId?: Prisma.StringFilter<"FooterSocial"> | string
  footer?: Prisma.XOR<Prisma.FooterScalarRelationFilter, Prisma.FooterWhereInput>
}

export type FooterSocialOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  footerId?: Prisma.SortOrder
  footer?: Prisma.FooterOrderByWithRelationInput
}

export type FooterSocialWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FooterSocialWhereInput | Prisma.FooterSocialWhereInput[]
  OR?: Prisma.FooterSocialWhereInput[]
  NOT?: Prisma.FooterSocialWhereInput | Prisma.FooterSocialWhereInput[]
  name?: Prisma.StringFilter<"FooterSocial"> | string
  icon?: Prisma.StringNullableFilter<"FooterSocial"> | string | null
  url?: Prisma.StringFilter<"FooterSocial"> | string
  footerId?: Prisma.StringFilter<"FooterSocial"> | string
  footer?: Prisma.XOR<Prisma.FooterScalarRelationFilter, Prisma.FooterWhereInput>
}, "id">

export type FooterSocialOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  footerId?: Prisma.SortOrder
  _count?: Prisma.FooterSocialCountOrderByAggregateInput
  _max?: Prisma.FooterSocialMaxOrderByAggregateInput
  _min?: Prisma.FooterSocialMinOrderByAggregateInput
}

export type FooterSocialScalarWhereWithAggregatesInput = {
  AND?: Prisma.FooterSocialScalarWhereWithAggregatesInput | Prisma.FooterSocialScalarWhereWithAggregatesInput[]
  OR?: Prisma.FooterSocialScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FooterSocialScalarWhereWithAggregatesInput | Prisma.FooterSocialScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FooterSocial"> | string
  name?: Prisma.StringWithAggregatesFilter<"FooterSocial"> | string
  icon?: Prisma.StringNullableWithAggregatesFilter<"FooterSocial"> | string | null
  url?: Prisma.StringWithAggregatesFilter<"FooterSocial"> | string
  footerId?: Prisma.StringWithAggregatesFilter<"FooterSocial"> | string
}

export type FooterSocialCreateInput = {
  id?: string
  name: string
  icon?: string | null
  url: string
  footer: Prisma.FooterCreateNestedOneWithoutSocialLinksInput
}

export type FooterSocialUncheckedCreateInput = {
  id?: string
  name: string
  icon?: string | null
  url: string
  footerId: string
}

export type FooterSocialUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  footer?: Prisma.FooterUpdateOneRequiredWithoutSocialLinksNestedInput
}

export type FooterSocialUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  footerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FooterSocialCreateManyInput = {
  id?: string
  name: string
  icon?: string | null
  url: string
  footerId: string
}

export type FooterSocialUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FooterSocialUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  footerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FooterSocialListRelationFilter = {
  every?: Prisma.FooterSocialWhereInput
  some?: Prisma.FooterSocialWhereInput
  none?: Prisma.FooterSocialWhereInput
}

export type FooterSocialOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FooterSocialCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  footerId?: Prisma.SortOrder
}

export type FooterSocialMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  footerId?: Prisma.SortOrder
}

export type FooterSocialMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  url?: Prisma.SortOrder
  footerId?: Prisma.SortOrder
}

export type FooterSocialCreateNestedManyWithoutFooterInput = {
  create?: Prisma.XOR<Prisma.FooterSocialCreateWithoutFooterInput, Prisma.FooterSocialUncheckedCreateWithoutFooterInput> | Prisma.FooterSocialCreateWithoutFooterInput[] | Prisma.FooterSocialUncheckedCreateWithoutFooterInput[]
  connectOrCreate?: Prisma.FooterSocialCreateOrConnectWithoutFooterInput | Prisma.FooterSocialCreateOrConnectWithoutFooterInput[]
  createMany?: Prisma.FooterSocialCreateManyFooterInputEnvelope
  connect?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
}

export type FooterSocialUncheckedCreateNestedManyWithoutFooterInput = {
  create?: Prisma.XOR<Prisma.FooterSocialCreateWithoutFooterInput, Prisma.FooterSocialUncheckedCreateWithoutFooterInput> | Prisma.FooterSocialCreateWithoutFooterInput[] | Prisma.FooterSocialUncheckedCreateWithoutFooterInput[]
  connectOrCreate?: Prisma.FooterSocialCreateOrConnectWithoutFooterInput | Prisma.FooterSocialCreateOrConnectWithoutFooterInput[]
  createMany?: Prisma.FooterSocialCreateManyFooterInputEnvelope
  connect?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
}

export type FooterSocialUpdateManyWithoutFooterNestedInput = {
  create?: Prisma.XOR<Prisma.FooterSocialCreateWithoutFooterInput, Prisma.FooterSocialUncheckedCreateWithoutFooterInput> | Prisma.FooterSocialCreateWithoutFooterInput[] | Prisma.FooterSocialUncheckedCreateWithoutFooterInput[]
  connectOrCreate?: Prisma.FooterSocialCreateOrConnectWithoutFooterInput | Prisma.FooterSocialCreateOrConnectWithoutFooterInput[]
  upsert?: Prisma.FooterSocialUpsertWithWhereUniqueWithoutFooterInput | Prisma.FooterSocialUpsertWithWhereUniqueWithoutFooterInput[]
  createMany?: Prisma.FooterSocialCreateManyFooterInputEnvelope
  set?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  disconnect?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  delete?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  connect?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  update?: Prisma.FooterSocialUpdateWithWhereUniqueWithoutFooterInput | Prisma.FooterSocialUpdateWithWhereUniqueWithoutFooterInput[]
  updateMany?: Prisma.FooterSocialUpdateManyWithWhereWithoutFooterInput | Prisma.FooterSocialUpdateManyWithWhereWithoutFooterInput[]
  deleteMany?: Prisma.FooterSocialScalarWhereInput | Prisma.FooterSocialScalarWhereInput[]
}

export type FooterSocialUncheckedUpdateManyWithoutFooterNestedInput = {
  create?: Prisma.XOR<Prisma.FooterSocialCreateWithoutFooterInput, Prisma.FooterSocialUncheckedCreateWithoutFooterInput> | Prisma.FooterSocialCreateWithoutFooterInput[] | Prisma.FooterSocialUncheckedCreateWithoutFooterInput[]
  connectOrCreate?: Prisma.FooterSocialCreateOrConnectWithoutFooterInput | Prisma.FooterSocialCreateOrConnectWithoutFooterInput[]
  upsert?: Prisma.FooterSocialUpsertWithWhereUniqueWithoutFooterInput | Prisma.FooterSocialUpsertWithWhereUniqueWithoutFooterInput[]
  createMany?: Prisma.FooterSocialCreateManyFooterInputEnvelope
  set?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  disconnect?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  delete?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  connect?: Prisma.FooterSocialWhereUniqueInput | Prisma.FooterSocialWhereUniqueInput[]
  update?: Prisma.FooterSocialUpdateWithWhereUniqueWithoutFooterInput | Prisma.FooterSocialUpdateWithWhereUniqueWithoutFooterInput[]
  updateMany?: Prisma.FooterSocialUpdateManyWithWhereWithoutFooterInput | Prisma.FooterSocialUpdateManyWithWhereWithoutFooterInput[]
  deleteMany?: Prisma.FooterSocialScalarWhereInput | Prisma.FooterSocialScalarWhereInput[]
}

export type FooterSocialCreateWithoutFooterInput = {
  id?: string
  name: string
  icon?: string | null
  url: string
}

export type FooterSocialUncheckedCreateWithoutFooterInput = {
  id?: string
  name: string
  icon?: string | null
  url: string
}

export type FooterSocialCreateOrConnectWithoutFooterInput = {
  where: Prisma.FooterSocialWhereUniqueInput
  create: Prisma.XOR<Prisma.FooterSocialCreateWithoutFooterInput, Prisma.FooterSocialUncheckedCreateWithoutFooterInput>
}

export type FooterSocialCreateManyFooterInputEnvelope = {
  data: Prisma.FooterSocialCreateManyFooterInput | Prisma.FooterSocialCreateManyFooterInput[]
  skipDuplicates?: boolean
}

export type FooterSocialUpsertWithWhereUniqueWithoutFooterInput = {
  where: Prisma.FooterSocialWhereUniqueInput
  update: Prisma.XOR<Prisma.FooterSocialUpdateWithoutFooterInput, Prisma.FooterSocialUncheckedUpdateWithoutFooterInput>
  create: Prisma.XOR<Prisma.FooterSocialCreateWithoutFooterInput, Prisma.FooterSocialUncheckedCreateWithoutFooterInput>
}

export type FooterSocialUpdateWithWhereUniqueWithoutFooterInput = {
  where: Prisma.FooterSocialWhereUniqueInput
  data: Prisma.XOR<Prisma.FooterSocialUpdateWithoutFooterInput, Prisma.FooterSocialUncheckedUpdateWithoutFooterInput>
}

export type FooterSocialUpdateManyWithWhereWithoutFooterInput = {
  where: Prisma.FooterSocialScalarWhereInput
  data: Prisma.XOR<Prisma.FooterSocialUpdateManyMutationInput, Prisma.FooterSocialUncheckedUpdateManyWithoutFooterInput>
}

export type FooterSocialScalarWhereInput = {
  AND?: Prisma.FooterSocialScalarWhereInput | Prisma.FooterSocialScalarWhereInput[]
  OR?: Prisma.FooterSocialScalarWhereInput[]
  NOT?: Prisma.FooterSocialScalarWhereInput | Prisma.FooterSocialScalarWhereInput[]
  id?: Prisma.StringFilter<"FooterSocial"> | string
  name?: Prisma.StringFilter<"FooterSocial"> | string
  icon?: Prisma.StringNullableFilter<"FooterSocial"> | string | null
  url?: Prisma.StringFilter<"FooterSocial"> | string
  footerId?: Prisma.StringFilter<"FooterSocial"> | string
}

export type FooterSocialCreateManyFooterInput = {
  id?: string
  name: string
  icon?: string | null
  url: string
}

export type FooterSocialUpdateWithoutFooterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FooterSocialUncheckedUpdateWithoutFooterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FooterSocialUncheckedUpdateManyWithoutFooterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FooterSocialSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  icon?: boolean
  url?: boolean
  footerId?: boolean
  footer?: boolean | Prisma.FooterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["footerSocial"]>

export type FooterSocialSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  icon?: boolean
  url?: boolean
  footerId?: boolean
  footer?: boolean | Prisma.FooterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["footerSocial"]>

export type FooterSocialSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  icon?: boolean
  url?: boolean
  footerId?: boolean
  footer?: boolean | Prisma.FooterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["footerSocial"]>

export type FooterSocialSelectScalar = {
  id?: boolean
  name?: boolean
  icon?: boolean
  url?: boolean
  footerId?: boolean
}

export type FooterSocialOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "icon" | "url" | "footerId", ExtArgs["result"]["footerSocial"]>
export type FooterSocialInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  footer?: boolean | Prisma.FooterDefaultArgs<ExtArgs>
}
export type FooterSocialIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  footer?: boolean | Prisma.FooterDefaultArgs<ExtArgs>
}
export type FooterSocialIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  footer?: boolean | Prisma.FooterDefaultArgs<ExtArgs>
}

export type $FooterSocialPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FooterSocial"
  objects: {
    footer: Prisma.$FooterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    icon: string | null
    url: string
    footerId: string
  }, ExtArgs["result"]["footerSocial"]>
  composites: {}
}

export type FooterSocialGetPayload<S extends boolean | null | undefined | FooterSocialDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload, S>

export type FooterSocialCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FooterSocialFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FooterSocialCountAggregateInputType | true
  }

export interface FooterSocialDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FooterSocial'], meta: { name: 'FooterSocial' } }
  /**
   * Find zero or one FooterSocial that matches the filter.
   * @param {FooterSocialFindUniqueArgs} args - Arguments to find a FooterSocial
   * @example
   * // Get one FooterSocial
   * const footerSocial = await prisma.footerSocial.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FooterSocialFindUniqueArgs>(args: Prisma.SelectSubset<T, FooterSocialFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FooterSocial that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FooterSocialFindUniqueOrThrowArgs} args - Arguments to find a FooterSocial
   * @example
   * // Get one FooterSocial
   * const footerSocial = await prisma.footerSocial.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FooterSocialFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FooterSocialFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterSocial that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialFindFirstArgs} args - Arguments to find a FooterSocial
   * @example
   * // Get one FooterSocial
   * const footerSocial = await prisma.footerSocial.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FooterSocialFindFirstArgs>(args?: Prisma.SelectSubset<T, FooterSocialFindFirstArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FooterSocial that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialFindFirstOrThrowArgs} args - Arguments to find a FooterSocial
   * @example
   * // Get one FooterSocial
   * const footerSocial = await prisma.footerSocial.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FooterSocialFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FooterSocialFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FooterSocials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FooterSocials
   * const footerSocials = await prisma.footerSocial.findMany()
   * 
   * // Get first 10 FooterSocials
   * const footerSocials = await prisma.footerSocial.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const footerSocialWithIdOnly = await prisma.footerSocial.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FooterSocialFindManyArgs>(args?: Prisma.SelectSubset<T, FooterSocialFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FooterSocial.
   * @param {FooterSocialCreateArgs} args - Arguments to create a FooterSocial.
   * @example
   * // Create one FooterSocial
   * const FooterSocial = await prisma.footerSocial.create({
   *   data: {
   *     // ... data to create a FooterSocial
   *   }
   * })
   * 
   */
  create<T extends FooterSocialCreateArgs>(args: Prisma.SelectSubset<T, FooterSocialCreateArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FooterSocials.
   * @param {FooterSocialCreateManyArgs} args - Arguments to create many FooterSocials.
   * @example
   * // Create many FooterSocials
   * const footerSocial = await prisma.footerSocial.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FooterSocialCreateManyArgs>(args?: Prisma.SelectSubset<T, FooterSocialCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FooterSocials and returns the data saved in the database.
   * @param {FooterSocialCreateManyAndReturnArgs} args - Arguments to create many FooterSocials.
   * @example
   * // Create many FooterSocials
   * const footerSocial = await prisma.footerSocial.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FooterSocials and only return the `id`
   * const footerSocialWithIdOnly = await prisma.footerSocial.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FooterSocialCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FooterSocialCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FooterSocial.
   * @param {FooterSocialDeleteArgs} args - Arguments to delete one FooterSocial.
   * @example
   * // Delete one FooterSocial
   * const FooterSocial = await prisma.footerSocial.delete({
   *   where: {
   *     // ... filter to delete one FooterSocial
   *   }
   * })
   * 
   */
  delete<T extends FooterSocialDeleteArgs>(args: Prisma.SelectSubset<T, FooterSocialDeleteArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FooterSocial.
   * @param {FooterSocialUpdateArgs} args - Arguments to update one FooterSocial.
   * @example
   * // Update one FooterSocial
   * const footerSocial = await prisma.footerSocial.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FooterSocialUpdateArgs>(args: Prisma.SelectSubset<T, FooterSocialUpdateArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FooterSocials.
   * @param {FooterSocialDeleteManyArgs} args - Arguments to filter FooterSocials to delete.
   * @example
   * // Delete a few FooterSocials
   * const { count } = await prisma.footerSocial.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FooterSocialDeleteManyArgs>(args?: Prisma.SelectSubset<T, FooterSocialDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterSocials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FooterSocials
   * const footerSocial = await prisma.footerSocial.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FooterSocialUpdateManyArgs>(args: Prisma.SelectSubset<T, FooterSocialUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FooterSocials and returns the data updated in the database.
   * @param {FooterSocialUpdateManyAndReturnArgs} args - Arguments to update many FooterSocials.
   * @example
   * // Update many FooterSocials
   * const footerSocial = await prisma.footerSocial.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FooterSocials and only return the `id`
   * const footerSocialWithIdOnly = await prisma.footerSocial.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FooterSocialUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FooterSocialUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FooterSocial.
   * @param {FooterSocialUpsertArgs} args - Arguments to update or create a FooterSocial.
   * @example
   * // Update or create a FooterSocial
   * const footerSocial = await prisma.footerSocial.upsert({
   *   create: {
   *     // ... data to create a FooterSocial
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FooterSocial we want to update
   *   }
   * })
   */
  upsert<T extends FooterSocialUpsertArgs>(args: Prisma.SelectSubset<T, FooterSocialUpsertArgs<ExtArgs>>): Prisma.Prisma__FooterSocialClient<runtime.Types.Result.GetResult<Prisma.$FooterSocialPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FooterSocials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialCountArgs} args - Arguments to filter FooterSocials to count.
   * @example
   * // Count the number of FooterSocials
   * const count = await prisma.footerSocial.count({
   *   where: {
   *     // ... the filter for the FooterSocials we want to count
   *   }
   * })
  **/
  count<T extends FooterSocialCountArgs>(
    args?: Prisma.Subset<T, FooterSocialCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FooterSocialCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FooterSocial.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FooterSocialAggregateArgs>(args: Prisma.Subset<T, FooterSocialAggregateArgs>): Prisma.PrismaPromise<GetFooterSocialAggregateType<T>>

  /**
   * Group by FooterSocial.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FooterSocialGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FooterSocialGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FooterSocialGroupByArgs['orderBy'] }
      : { orderBy?: FooterSocialGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FooterSocialGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFooterSocialGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FooterSocial model
 */
readonly fields: FooterSocialFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FooterSocial.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FooterSocialClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  footer<T extends Prisma.FooterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FooterDefaultArgs<ExtArgs>>): Prisma.Prisma__FooterClient<runtime.Types.Result.GetResult<Prisma.$FooterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FooterSocial model
 */
export interface FooterSocialFieldRefs {
  readonly id: Prisma.FieldRef<"FooterSocial", 'String'>
  readonly name: Prisma.FieldRef<"FooterSocial", 'String'>
  readonly icon: Prisma.FieldRef<"FooterSocial", 'String'>
  readonly url: Prisma.FieldRef<"FooterSocial", 'String'>
  readonly footerId: Prisma.FieldRef<"FooterSocial", 'String'>
}
    

// Custom InputTypes
/**
 * FooterSocial findUnique
 */
export type FooterSocialFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * Filter, which FooterSocial to fetch.
   */
  where: Prisma.FooterSocialWhereUniqueInput
}

/**
 * FooterSocial findUniqueOrThrow
 */
export type FooterSocialFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * Filter, which FooterSocial to fetch.
   */
  where: Prisma.FooterSocialWhereUniqueInput
}

/**
 * FooterSocial findFirst
 */
export type FooterSocialFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * Filter, which FooterSocial to fetch.
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocials to fetch.
   */
  orderBy?: Prisma.FooterSocialOrderByWithRelationInput | Prisma.FooterSocialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterSocials.
   */
  cursor?: Prisma.FooterSocialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterSocials.
   */
  distinct?: Prisma.FooterSocialScalarFieldEnum | Prisma.FooterSocialScalarFieldEnum[]
}

/**
 * FooterSocial findFirstOrThrow
 */
export type FooterSocialFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * Filter, which FooterSocial to fetch.
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocials to fetch.
   */
  orderBy?: Prisma.FooterSocialOrderByWithRelationInput | Prisma.FooterSocialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FooterSocials.
   */
  cursor?: Prisma.FooterSocialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterSocials.
   */
  distinct?: Prisma.FooterSocialScalarFieldEnum | Prisma.FooterSocialScalarFieldEnum[]
}

/**
 * FooterSocial findMany
 */
export type FooterSocialFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * Filter, which FooterSocials to fetch.
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FooterSocials to fetch.
   */
  orderBy?: Prisma.FooterSocialOrderByWithRelationInput | Prisma.FooterSocialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FooterSocials.
   */
  cursor?: Prisma.FooterSocialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FooterSocials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FooterSocials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FooterSocials.
   */
  distinct?: Prisma.FooterSocialScalarFieldEnum | Prisma.FooterSocialScalarFieldEnum[]
}

/**
 * FooterSocial create
 */
export type FooterSocialCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * The data needed to create a FooterSocial.
   */
  data: Prisma.XOR<Prisma.FooterSocialCreateInput, Prisma.FooterSocialUncheckedCreateInput>
}

/**
 * FooterSocial createMany
 */
export type FooterSocialCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FooterSocials.
   */
  data: Prisma.FooterSocialCreateManyInput | Prisma.FooterSocialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FooterSocial createManyAndReturn
 */
export type FooterSocialCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * The data used to create many FooterSocials.
   */
  data: Prisma.FooterSocialCreateManyInput | Prisma.FooterSocialCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FooterSocial update
 */
export type FooterSocialUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * The data needed to update a FooterSocial.
   */
  data: Prisma.XOR<Prisma.FooterSocialUpdateInput, Prisma.FooterSocialUncheckedUpdateInput>
  /**
   * Choose, which FooterSocial to update.
   */
  where: Prisma.FooterSocialWhereUniqueInput
}

/**
 * FooterSocial updateMany
 */
export type FooterSocialUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FooterSocials.
   */
  data: Prisma.XOR<Prisma.FooterSocialUpdateManyMutationInput, Prisma.FooterSocialUncheckedUpdateManyInput>
  /**
   * Filter which FooterSocials to update
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * Limit how many FooterSocials to update.
   */
  limit?: number
}

/**
 * FooterSocial updateManyAndReturn
 */
export type FooterSocialUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * The data used to update FooterSocials.
   */
  data: Prisma.XOR<Prisma.FooterSocialUpdateManyMutationInput, Prisma.FooterSocialUncheckedUpdateManyInput>
  /**
   * Filter which FooterSocials to update
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * Limit how many FooterSocials to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FooterSocial upsert
 */
export type FooterSocialUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * The filter to search for the FooterSocial to update in case it exists.
   */
  where: Prisma.FooterSocialWhereUniqueInput
  /**
   * In case the FooterSocial found by the `where` argument doesn't exist, create a new FooterSocial with this data.
   */
  create: Prisma.XOR<Prisma.FooterSocialCreateInput, Prisma.FooterSocialUncheckedCreateInput>
  /**
   * In case the FooterSocial was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FooterSocialUpdateInput, Prisma.FooterSocialUncheckedUpdateInput>
}

/**
 * FooterSocial delete
 */
export type FooterSocialDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
  /**
   * Filter which FooterSocial to delete.
   */
  where: Prisma.FooterSocialWhereUniqueInput
}

/**
 * FooterSocial deleteMany
 */
export type FooterSocialDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FooterSocials to delete
   */
  where?: Prisma.FooterSocialWhereInput
  /**
   * Limit how many FooterSocials to delete.
   */
  limit?: number
}

/**
 * FooterSocial without action
 */
export type FooterSocialDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FooterSocial
   */
  select?: Prisma.FooterSocialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FooterSocial
   */
  omit?: Prisma.FooterSocialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FooterSocialInclude<ExtArgs> | null
}
