
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductBenefit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ProductBenefit
 * 
 */
export type ProductBenefitModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductBenefitPayload>

export type AggregateProductBenefit = {
  _count: ProductBenefitCountAggregateOutputType | null
  _min: ProductBenefitMinAggregateOutputType | null
  _max: ProductBenefitMaxAggregateOutputType | null
}

export type ProductBenefitMinAggregateOutputType = {
  id: string | null
  productId: string | null
  title: string | null
}

export type ProductBenefitMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  title: string | null
}

export type ProductBenefitCountAggregateOutputType = {
  id: number
  productId: number
  title: number
  _all: number
}


export type ProductBenefitMinAggregateInputType = {
  id?: true
  productId?: true
  title?: true
}

export type ProductBenefitMaxAggregateInputType = {
  id?: true
  productId?: true
  title?: true
}

export type ProductBenefitCountAggregateInputType = {
  id?: true
  productId?: true
  title?: true
  _all?: true
}

export type ProductBenefitAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductBenefit to aggregate.
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductBenefits to fetch.
   */
  orderBy?: Prisma.ProductBenefitOrderByWithRelationInput | Prisma.ProductBenefitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductBenefitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductBenefits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductBenefits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductBenefits
  **/
  _count?: true | ProductBenefitCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductBenefitMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductBenefitMaxAggregateInputType
}

export type GetProductBenefitAggregateType<T extends ProductBenefitAggregateArgs> = {
      [P in keyof T & keyof AggregateProductBenefit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductBenefit[P]>
    : Prisma.GetScalarType<T[P], AggregateProductBenefit[P]>
}




export type ProductBenefitGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductBenefitWhereInput
  orderBy?: Prisma.ProductBenefitOrderByWithAggregationInput | Prisma.ProductBenefitOrderByWithAggregationInput[]
  by: Prisma.ProductBenefitScalarFieldEnum[] | Prisma.ProductBenefitScalarFieldEnum
  having?: Prisma.ProductBenefitScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductBenefitCountAggregateInputType | true
  _min?: ProductBenefitMinAggregateInputType
  _max?: ProductBenefitMaxAggregateInputType
}

export type ProductBenefitGroupByOutputType = {
  id: string
  productId: string
  title: string
  _count: ProductBenefitCountAggregateOutputType | null
  _min: ProductBenefitMinAggregateOutputType | null
  _max: ProductBenefitMaxAggregateOutputType | null
}

export type GetProductBenefitGroupByPayload<T extends ProductBenefitGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductBenefitGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductBenefitGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductBenefitGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductBenefitGroupByOutputType[P]>
      }
    >
  >



export type ProductBenefitWhereInput = {
  AND?: Prisma.ProductBenefitWhereInput | Prisma.ProductBenefitWhereInput[]
  OR?: Prisma.ProductBenefitWhereInput[]
  NOT?: Prisma.ProductBenefitWhereInput | Prisma.ProductBenefitWhereInput[]
  id?: Prisma.StringFilter<"ProductBenefit"> | string
  productId?: Prisma.StringFilter<"ProductBenefit"> | string
  title?: Prisma.StringFilter<"ProductBenefit"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductBenefitOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ProductBenefitWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProductBenefitWhereInput | Prisma.ProductBenefitWhereInput[]
  OR?: Prisma.ProductBenefitWhereInput[]
  NOT?: Prisma.ProductBenefitWhereInput | Prisma.ProductBenefitWhereInput[]
  productId?: Prisma.StringFilter<"ProductBenefit"> | string
  title?: Prisma.StringFilter<"ProductBenefit"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type ProductBenefitOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  _count?: Prisma.ProductBenefitCountOrderByAggregateInput
  _max?: Prisma.ProductBenefitMaxOrderByAggregateInput
  _min?: Prisma.ProductBenefitMinOrderByAggregateInput
}

export type ProductBenefitScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductBenefitScalarWhereWithAggregatesInput | Prisma.ProductBenefitScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductBenefitScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductBenefitScalarWhereWithAggregatesInput | Prisma.ProductBenefitScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductBenefit"> | string
  productId?: Prisma.StringWithAggregatesFilter<"ProductBenefit"> | string
  title?: Prisma.StringWithAggregatesFilter<"ProductBenefit"> | string
}

export type ProductBenefitCreateInput = {
  id?: string
  title: string
  product: Prisma.ProductCreateNestedOneWithoutBenefitsInput
}

export type ProductBenefitUncheckedCreateInput = {
  id?: string
  productId: string
  title: string
}

export type ProductBenefitUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.ProductUpdateOneRequiredWithoutBenefitsNestedInput
}

export type ProductBenefitUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductBenefitCreateManyInput = {
  id?: string
  productId: string
  title: string
}

export type ProductBenefitUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductBenefitUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductBenefitListRelationFilter = {
  every?: Prisma.ProductBenefitWhereInput
  some?: Prisma.ProductBenefitWhereInput
  none?: Prisma.ProductBenefitWhereInput
}

export type ProductBenefitOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductBenefitCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type ProductBenefitMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type ProductBenefitMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type ProductBenefitCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductBenefitCreateWithoutProductInput, Prisma.ProductBenefitUncheckedCreateWithoutProductInput> | Prisma.ProductBenefitCreateWithoutProductInput[] | Prisma.ProductBenefitUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductBenefitCreateOrConnectWithoutProductInput | Prisma.ProductBenefitCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductBenefitCreateManyProductInputEnvelope
  connect?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
}

export type ProductBenefitUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductBenefitCreateWithoutProductInput, Prisma.ProductBenefitUncheckedCreateWithoutProductInput> | Prisma.ProductBenefitCreateWithoutProductInput[] | Prisma.ProductBenefitUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductBenefitCreateOrConnectWithoutProductInput | Prisma.ProductBenefitCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductBenefitCreateManyProductInputEnvelope
  connect?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
}

export type ProductBenefitUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductBenefitCreateWithoutProductInput, Prisma.ProductBenefitUncheckedCreateWithoutProductInput> | Prisma.ProductBenefitCreateWithoutProductInput[] | Prisma.ProductBenefitUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductBenefitCreateOrConnectWithoutProductInput | Prisma.ProductBenefitCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductBenefitUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductBenefitUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductBenefitCreateManyProductInputEnvelope
  set?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  disconnect?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  delete?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  connect?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  update?: Prisma.ProductBenefitUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductBenefitUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductBenefitUpdateManyWithWhereWithoutProductInput | Prisma.ProductBenefitUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductBenefitScalarWhereInput | Prisma.ProductBenefitScalarWhereInput[]
}

export type ProductBenefitUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductBenefitCreateWithoutProductInput, Prisma.ProductBenefitUncheckedCreateWithoutProductInput> | Prisma.ProductBenefitCreateWithoutProductInput[] | Prisma.ProductBenefitUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductBenefitCreateOrConnectWithoutProductInput | Prisma.ProductBenefitCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductBenefitUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductBenefitUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductBenefitCreateManyProductInputEnvelope
  set?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  disconnect?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  delete?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  connect?: Prisma.ProductBenefitWhereUniqueInput | Prisma.ProductBenefitWhereUniqueInput[]
  update?: Prisma.ProductBenefitUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductBenefitUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductBenefitUpdateManyWithWhereWithoutProductInput | Prisma.ProductBenefitUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductBenefitScalarWhereInput | Prisma.ProductBenefitScalarWhereInput[]
}

export type ProductBenefitCreateWithoutProductInput = {
  id?: string
  title: string
}

export type ProductBenefitUncheckedCreateWithoutProductInput = {
  id?: string
  title: string
}

export type ProductBenefitCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductBenefitWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductBenefitCreateWithoutProductInput, Prisma.ProductBenefitUncheckedCreateWithoutProductInput>
}

export type ProductBenefitCreateManyProductInputEnvelope = {
  data: Prisma.ProductBenefitCreateManyProductInput | Prisma.ProductBenefitCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type ProductBenefitUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductBenefitWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductBenefitUpdateWithoutProductInput, Prisma.ProductBenefitUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductBenefitCreateWithoutProductInput, Prisma.ProductBenefitUncheckedCreateWithoutProductInput>
}

export type ProductBenefitUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductBenefitWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductBenefitUpdateWithoutProductInput, Prisma.ProductBenefitUncheckedUpdateWithoutProductInput>
}

export type ProductBenefitUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductBenefitScalarWhereInput
  data: Prisma.XOR<Prisma.ProductBenefitUpdateManyMutationInput, Prisma.ProductBenefitUncheckedUpdateManyWithoutProductInput>
}

export type ProductBenefitScalarWhereInput = {
  AND?: Prisma.ProductBenefitScalarWhereInput | Prisma.ProductBenefitScalarWhereInput[]
  OR?: Prisma.ProductBenefitScalarWhereInput[]
  NOT?: Prisma.ProductBenefitScalarWhereInput | Prisma.ProductBenefitScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductBenefit"> | string
  productId?: Prisma.StringFilter<"ProductBenefit"> | string
  title?: Prisma.StringFilter<"ProductBenefit"> | string
}

export type ProductBenefitCreateManyProductInput = {
  id?: string
  title: string
}

export type ProductBenefitUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductBenefitUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductBenefitUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ProductBenefitSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  title?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productBenefit"]>

export type ProductBenefitSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  title?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productBenefit"]>

export type ProductBenefitSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  title?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productBenefit"]>

export type ProductBenefitSelectScalar = {
  id?: boolean
  productId?: boolean
  title?: boolean
}

export type ProductBenefitOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "title", ExtArgs["result"]["productBenefit"]>
export type ProductBenefitInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductBenefitIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductBenefitIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductBenefitPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductBenefit"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    title: string
  }, ExtArgs["result"]["productBenefit"]>
  composites: {}
}

export type ProductBenefitGetPayload<S extends boolean | null | undefined | ProductBenefitDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload, S>

export type ProductBenefitCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductBenefitFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductBenefitCountAggregateInputType | true
  }

export interface ProductBenefitDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductBenefit'], meta: { name: 'ProductBenefit' } }
  /**
   * Find zero or one ProductBenefit that matches the filter.
   * @param {ProductBenefitFindUniqueArgs} args - Arguments to find a ProductBenefit
   * @example
   * // Get one ProductBenefit
   * const productBenefit = await prisma.productBenefit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductBenefitFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductBenefitFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductBenefit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductBenefitFindUniqueOrThrowArgs} args - Arguments to find a ProductBenefit
   * @example
   * // Get one ProductBenefit
   * const productBenefit = await prisma.productBenefit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductBenefitFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductBenefitFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductBenefit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitFindFirstArgs} args - Arguments to find a ProductBenefit
   * @example
   * // Get one ProductBenefit
   * const productBenefit = await prisma.productBenefit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductBenefitFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductBenefitFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductBenefit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitFindFirstOrThrowArgs} args - Arguments to find a ProductBenefit
   * @example
   * // Get one ProductBenefit
   * const productBenefit = await prisma.productBenefit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductBenefitFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductBenefitFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductBenefits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductBenefits
   * const productBenefits = await prisma.productBenefit.findMany()
   * 
   * // Get first 10 ProductBenefits
   * const productBenefits = await prisma.productBenefit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productBenefitWithIdOnly = await prisma.productBenefit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductBenefitFindManyArgs>(args?: Prisma.SelectSubset<T, ProductBenefitFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductBenefit.
   * @param {ProductBenefitCreateArgs} args - Arguments to create a ProductBenefit.
   * @example
   * // Create one ProductBenefit
   * const ProductBenefit = await prisma.productBenefit.create({
   *   data: {
   *     // ... data to create a ProductBenefit
   *   }
   * })
   * 
   */
  create<T extends ProductBenefitCreateArgs>(args: Prisma.SelectSubset<T, ProductBenefitCreateArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductBenefits.
   * @param {ProductBenefitCreateManyArgs} args - Arguments to create many ProductBenefits.
   * @example
   * // Create many ProductBenefits
   * const productBenefit = await prisma.productBenefit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductBenefitCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductBenefitCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductBenefits and returns the data saved in the database.
   * @param {ProductBenefitCreateManyAndReturnArgs} args - Arguments to create many ProductBenefits.
   * @example
   * // Create many ProductBenefits
   * const productBenefit = await prisma.productBenefit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductBenefits and only return the `id`
   * const productBenefitWithIdOnly = await prisma.productBenefit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductBenefitCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductBenefitCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductBenefit.
   * @param {ProductBenefitDeleteArgs} args - Arguments to delete one ProductBenefit.
   * @example
   * // Delete one ProductBenefit
   * const ProductBenefit = await prisma.productBenefit.delete({
   *   where: {
   *     // ... filter to delete one ProductBenefit
   *   }
   * })
   * 
   */
  delete<T extends ProductBenefitDeleteArgs>(args: Prisma.SelectSubset<T, ProductBenefitDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductBenefit.
   * @param {ProductBenefitUpdateArgs} args - Arguments to update one ProductBenefit.
   * @example
   * // Update one ProductBenefit
   * const productBenefit = await prisma.productBenefit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductBenefitUpdateArgs>(args: Prisma.SelectSubset<T, ProductBenefitUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductBenefits.
   * @param {ProductBenefitDeleteManyArgs} args - Arguments to filter ProductBenefits to delete.
   * @example
   * // Delete a few ProductBenefits
   * const { count } = await prisma.productBenefit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductBenefitDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductBenefitDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductBenefits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductBenefits
   * const productBenefit = await prisma.productBenefit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductBenefitUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductBenefitUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductBenefits and returns the data updated in the database.
   * @param {ProductBenefitUpdateManyAndReturnArgs} args - Arguments to update many ProductBenefits.
   * @example
   * // Update many ProductBenefits
   * const productBenefit = await prisma.productBenefit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductBenefits and only return the `id`
   * const productBenefitWithIdOnly = await prisma.productBenefit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductBenefitUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductBenefitUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductBenefit.
   * @param {ProductBenefitUpsertArgs} args - Arguments to update or create a ProductBenefit.
   * @example
   * // Update or create a ProductBenefit
   * const productBenefit = await prisma.productBenefit.upsert({
   *   create: {
   *     // ... data to create a ProductBenefit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductBenefit we want to update
   *   }
   * })
   */
  upsert<T extends ProductBenefitUpsertArgs>(args: Prisma.SelectSubset<T, ProductBenefitUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductBenefitClient<runtime.Types.Result.GetResult<Prisma.$ProductBenefitPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductBenefits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitCountArgs} args - Arguments to filter ProductBenefits to count.
   * @example
   * // Count the number of ProductBenefits
   * const count = await prisma.productBenefit.count({
   *   where: {
   *     // ... the filter for the ProductBenefits we want to count
   *   }
   * })
  **/
  count<T extends ProductBenefitCountArgs>(
    args?: Prisma.Subset<T, ProductBenefitCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductBenefitCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductBenefit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductBenefitAggregateArgs>(args: Prisma.Subset<T, ProductBenefitAggregateArgs>): Prisma.PrismaPromise<GetProductBenefitAggregateType<T>>

  /**
   * Group by ProductBenefit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductBenefitGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductBenefitGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductBenefitGroupByArgs['orderBy'] }
      : { orderBy?: ProductBenefitGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductBenefitGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductBenefitGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductBenefit model
 */
readonly fields: ProductBenefitFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductBenefit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductBenefitClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductBenefit model
 */
export interface ProductBenefitFieldRefs {
  readonly id: Prisma.FieldRef<"ProductBenefit", 'String'>
  readonly productId: Prisma.FieldRef<"ProductBenefit", 'String'>
  readonly title: Prisma.FieldRef<"ProductBenefit", 'String'>
}
    

// Custom InputTypes
/**
 * ProductBenefit findUnique
 */
export type ProductBenefitFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * Filter, which ProductBenefit to fetch.
   */
  where: Prisma.ProductBenefitWhereUniqueInput
}

/**
 * ProductBenefit findUniqueOrThrow
 */
export type ProductBenefitFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * Filter, which ProductBenefit to fetch.
   */
  where: Prisma.ProductBenefitWhereUniqueInput
}

/**
 * ProductBenefit findFirst
 */
export type ProductBenefitFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * Filter, which ProductBenefit to fetch.
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductBenefits to fetch.
   */
  orderBy?: Prisma.ProductBenefitOrderByWithRelationInput | Prisma.ProductBenefitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductBenefits.
   */
  cursor?: Prisma.ProductBenefitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductBenefits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductBenefits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductBenefits.
   */
  distinct?: Prisma.ProductBenefitScalarFieldEnum | Prisma.ProductBenefitScalarFieldEnum[]
}

/**
 * ProductBenefit findFirstOrThrow
 */
export type ProductBenefitFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * Filter, which ProductBenefit to fetch.
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductBenefits to fetch.
   */
  orderBy?: Prisma.ProductBenefitOrderByWithRelationInput | Prisma.ProductBenefitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductBenefits.
   */
  cursor?: Prisma.ProductBenefitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductBenefits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductBenefits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductBenefits.
   */
  distinct?: Prisma.ProductBenefitScalarFieldEnum | Prisma.ProductBenefitScalarFieldEnum[]
}

/**
 * ProductBenefit findMany
 */
export type ProductBenefitFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * Filter, which ProductBenefits to fetch.
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductBenefits to fetch.
   */
  orderBy?: Prisma.ProductBenefitOrderByWithRelationInput | Prisma.ProductBenefitOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductBenefits.
   */
  cursor?: Prisma.ProductBenefitWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductBenefits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductBenefits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductBenefits.
   */
  distinct?: Prisma.ProductBenefitScalarFieldEnum | Prisma.ProductBenefitScalarFieldEnum[]
}

/**
 * ProductBenefit create
 */
export type ProductBenefitCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductBenefit.
   */
  data: Prisma.XOR<Prisma.ProductBenefitCreateInput, Prisma.ProductBenefitUncheckedCreateInput>
}

/**
 * ProductBenefit createMany
 */
export type ProductBenefitCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductBenefits.
   */
  data: Prisma.ProductBenefitCreateManyInput | Prisma.ProductBenefitCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductBenefit createManyAndReturn
 */
export type ProductBenefitCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * The data used to create many ProductBenefits.
   */
  data: Prisma.ProductBenefitCreateManyInput | Prisma.ProductBenefitCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductBenefit update
 */
export type ProductBenefitUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductBenefit.
   */
  data: Prisma.XOR<Prisma.ProductBenefitUpdateInput, Prisma.ProductBenefitUncheckedUpdateInput>
  /**
   * Choose, which ProductBenefit to update.
   */
  where: Prisma.ProductBenefitWhereUniqueInput
}

/**
 * ProductBenefit updateMany
 */
export type ProductBenefitUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductBenefits.
   */
  data: Prisma.XOR<Prisma.ProductBenefitUpdateManyMutationInput, Prisma.ProductBenefitUncheckedUpdateManyInput>
  /**
   * Filter which ProductBenefits to update
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * Limit how many ProductBenefits to update.
   */
  limit?: number
}

/**
 * ProductBenefit updateManyAndReturn
 */
export type ProductBenefitUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * The data used to update ProductBenefits.
   */
  data: Prisma.XOR<Prisma.ProductBenefitUpdateManyMutationInput, Prisma.ProductBenefitUncheckedUpdateManyInput>
  /**
   * Filter which ProductBenefits to update
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * Limit how many ProductBenefits to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductBenefit upsert
 */
export type ProductBenefitUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductBenefit to update in case it exists.
   */
  where: Prisma.ProductBenefitWhereUniqueInput
  /**
   * In case the ProductBenefit found by the `where` argument doesn't exist, create a new ProductBenefit with this data.
   */
  create: Prisma.XOR<Prisma.ProductBenefitCreateInput, Prisma.ProductBenefitUncheckedCreateInput>
  /**
   * In case the ProductBenefit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductBenefitUpdateInput, Prisma.ProductBenefitUncheckedUpdateInput>
}

/**
 * ProductBenefit delete
 */
export type ProductBenefitDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
  /**
   * Filter which ProductBenefit to delete.
   */
  where: Prisma.ProductBenefitWhereUniqueInput
}

/**
 * ProductBenefit deleteMany
 */
export type ProductBenefitDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductBenefits to delete
   */
  where?: Prisma.ProductBenefitWhereInput
  /**
   * Limit how many ProductBenefits to delete.
   */
  limit?: number
}

/**
 * ProductBenefit without action
 */
export type ProductBenefitDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductBenefit
   */
  select?: Prisma.ProductBenefitSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductBenefit
   */
  omit?: Prisma.ProductBenefitOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductBenefitInclude<ExtArgs> | null
}
