
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductSEO` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ProductSEO
 * 
 */
export type ProductSEOModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductSEOPayload>

export type AggregateProductSEO = {
  _count: ProductSEOCountAggregateOutputType | null
  _min: ProductSEOMinAggregateOutputType | null
  _max: ProductSEOMaxAggregateOutputType | null
}

export type ProductSEOMinAggregateOutputType = {
  id: string | null
  productId: string | null
  metaTitle: string | null
  metaDescription: string | null
  metaKeyword: string | null
}

export type ProductSEOMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  metaTitle: string | null
  metaDescription: string | null
  metaKeyword: string | null
}

export type ProductSEOCountAggregateOutputType = {
  id: number
  productId: number
  metaTitle: number
  metaDescription: number
  metaKeyword: number
  _all: number
}


export type ProductSEOMinAggregateInputType = {
  id?: true
  productId?: true
  metaTitle?: true
  metaDescription?: true
  metaKeyword?: true
}

export type ProductSEOMaxAggregateInputType = {
  id?: true
  productId?: true
  metaTitle?: true
  metaDescription?: true
  metaKeyword?: true
}

export type ProductSEOCountAggregateInputType = {
  id?: true
  productId?: true
  metaTitle?: true
  metaDescription?: true
  metaKeyword?: true
  _all?: true
}

export type ProductSEOAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductSEO to aggregate.
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductSEOS to fetch.
   */
  orderBy?: Prisma.ProductSEOOrderByWithRelationInput | Prisma.ProductSEOOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductSEOWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductSEOS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductSEOS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductSEOS
  **/
  _count?: true | ProductSEOCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductSEOMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductSEOMaxAggregateInputType
}

export type GetProductSEOAggregateType<T extends ProductSEOAggregateArgs> = {
      [P in keyof T & keyof AggregateProductSEO]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductSEO[P]>
    : Prisma.GetScalarType<T[P], AggregateProductSEO[P]>
}




export type ProductSEOGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductSEOWhereInput
  orderBy?: Prisma.ProductSEOOrderByWithAggregationInput | Prisma.ProductSEOOrderByWithAggregationInput[]
  by: Prisma.ProductSEOScalarFieldEnum[] | Prisma.ProductSEOScalarFieldEnum
  having?: Prisma.ProductSEOScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductSEOCountAggregateInputType | true
  _min?: ProductSEOMinAggregateInputType
  _max?: ProductSEOMaxAggregateInputType
}

export type ProductSEOGroupByOutputType = {
  id: string
  productId: string
  metaTitle: string | null
  metaDescription: string | null
  metaKeyword: string | null
  _count: ProductSEOCountAggregateOutputType | null
  _min: ProductSEOMinAggregateOutputType | null
  _max: ProductSEOMaxAggregateOutputType | null
}

export type GetProductSEOGroupByPayload<T extends ProductSEOGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductSEOGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductSEOGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductSEOGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductSEOGroupByOutputType[P]>
      }
    >
  >



export type ProductSEOWhereInput = {
  AND?: Prisma.ProductSEOWhereInput | Prisma.ProductSEOWhereInput[]
  OR?: Prisma.ProductSEOWhereInput[]
  NOT?: Prisma.ProductSEOWhereInput | Prisma.ProductSEOWhereInput[]
  id?: Prisma.StringFilter<"ProductSEO"> | string
  productId?: Prisma.StringFilter<"ProductSEO"> | string
  metaTitle?: Prisma.StringNullableFilter<"ProductSEO"> | string | null
  metaDescription?: Prisma.StringNullableFilter<"ProductSEO"> | string | null
  metaKeyword?: Prisma.StringNullableFilter<"ProductSEO"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductSEOOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  metaDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  metaKeyword?: Prisma.SortOrderInput | Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ProductSEOWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  productId?: string
  AND?: Prisma.ProductSEOWhereInput | Prisma.ProductSEOWhereInput[]
  OR?: Prisma.ProductSEOWhereInput[]
  NOT?: Prisma.ProductSEOWhereInput | Prisma.ProductSEOWhereInput[]
  metaTitle?: Prisma.StringNullableFilter<"ProductSEO"> | string | null
  metaDescription?: Prisma.StringNullableFilter<"ProductSEO"> | string | null
  metaKeyword?: Prisma.StringNullableFilter<"ProductSEO"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "productId">

export type ProductSEOOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  metaDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  metaKeyword?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProductSEOCountOrderByAggregateInput
  _max?: Prisma.ProductSEOMaxOrderByAggregateInput
  _min?: Prisma.ProductSEOMinOrderByAggregateInput
}

export type ProductSEOScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductSEOScalarWhereWithAggregatesInput | Prisma.ProductSEOScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductSEOScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductSEOScalarWhereWithAggregatesInput | Prisma.ProductSEOScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductSEO"> | string
  productId?: Prisma.StringWithAggregatesFilter<"ProductSEO"> | string
  metaTitle?: Prisma.StringNullableWithAggregatesFilter<"ProductSEO"> | string | null
  metaDescription?: Prisma.StringNullableWithAggregatesFilter<"ProductSEO"> | string | null
  metaKeyword?: Prisma.StringNullableWithAggregatesFilter<"ProductSEO"> | string | null
}

export type ProductSEOCreateInput = {
  id?: string
  metaTitle?: string | null
  metaDescription?: string | null
  metaKeyword?: string | null
  product: Prisma.ProductCreateNestedOneWithoutSeoInput
}

export type ProductSEOUncheckedCreateInput = {
  id?: string
  productId: string
  metaTitle?: string | null
  metaDescription?: string | null
  metaKeyword?: string | null
}

export type ProductSEOUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaKeyword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutSeoNestedInput
}

export type ProductSEOUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaKeyword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductSEOCreateManyInput = {
  id?: string
  productId: string
  metaTitle?: string | null
  metaDescription?: string | null
  metaKeyword?: string | null
}

export type ProductSEOUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaKeyword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductSEOUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaKeyword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductSEONullableScalarRelationFilter = {
  is?: Prisma.ProductSEOWhereInput | null
  isNot?: Prisma.ProductSEOWhereInput | null
}

export type ProductSEOCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrder
  metaDescription?: Prisma.SortOrder
  metaKeyword?: Prisma.SortOrder
}

export type ProductSEOMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrder
  metaDescription?: Prisma.SortOrder
  metaKeyword?: Prisma.SortOrder
}

export type ProductSEOMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  metaTitle?: Prisma.SortOrder
  metaDescription?: Prisma.SortOrder
  metaKeyword?: Prisma.SortOrder
}

export type ProductSEOCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductSEOCreateWithoutProductInput, Prisma.ProductSEOUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductSEOCreateOrConnectWithoutProductInput
  connect?: Prisma.ProductSEOWhereUniqueInput
}

export type ProductSEOUncheckedCreateNestedOneWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductSEOCreateWithoutProductInput, Prisma.ProductSEOUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductSEOCreateOrConnectWithoutProductInput
  connect?: Prisma.ProductSEOWhereUniqueInput
}

export type ProductSEOUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductSEOCreateWithoutProductInput, Prisma.ProductSEOUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductSEOCreateOrConnectWithoutProductInput
  upsert?: Prisma.ProductSEOUpsertWithoutProductInput
  disconnect?: Prisma.ProductSEOWhereInput | boolean
  delete?: Prisma.ProductSEOWhereInput | boolean
  connect?: Prisma.ProductSEOWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductSEOUpdateToOneWithWhereWithoutProductInput, Prisma.ProductSEOUpdateWithoutProductInput>, Prisma.ProductSEOUncheckedUpdateWithoutProductInput>
}

export type ProductSEOUncheckedUpdateOneWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductSEOCreateWithoutProductInput, Prisma.ProductSEOUncheckedCreateWithoutProductInput>
  connectOrCreate?: Prisma.ProductSEOCreateOrConnectWithoutProductInput
  upsert?: Prisma.ProductSEOUpsertWithoutProductInput
  disconnect?: Prisma.ProductSEOWhereInput | boolean
  delete?: Prisma.ProductSEOWhereInput | boolean
  connect?: Prisma.ProductSEOWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProductSEOUpdateToOneWithWhereWithoutProductInput, Prisma.ProductSEOUpdateWithoutProductInput>, Prisma.ProductSEOUncheckedUpdateWithoutProductInput>
}

export type ProductSEOCreateWithoutProductInput = {
  id?: string
  metaTitle?: string | null
  metaDescription?: string | null
  metaKeyword?: string | null
}

export type ProductSEOUncheckedCreateWithoutProductInput = {
  id?: string
  metaTitle?: string | null
  metaDescription?: string | null
  metaKeyword?: string | null
}

export type ProductSEOCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductSEOWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductSEOCreateWithoutProductInput, Prisma.ProductSEOUncheckedCreateWithoutProductInput>
}

export type ProductSEOUpsertWithoutProductInput = {
  update: Prisma.XOR<Prisma.ProductSEOUpdateWithoutProductInput, Prisma.ProductSEOUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductSEOCreateWithoutProductInput, Prisma.ProductSEOUncheckedCreateWithoutProductInput>
  where?: Prisma.ProductSEOWhereInput
}

export type ProductSEOUpdateToOneWithWhereWithoutProductInput = {
  where?: Prisma.ProductSEOWhereInput
  data: Prisma.XOR<Prisma.ProductSEOUpdateWithoutProductInput, Prisma.ProductSEOUncheckedUpdateWithoutProductInput>
}

export type ProductSEOUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaKeyword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductSEOUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  metaTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metaKeyword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ProductSEOSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  metaKeyword?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productSEO"]>

export type ProductSEOSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  metaKeyword?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productSEO"]>

export type ProductSEOSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  metaKeyword?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productSEO"]>

export type ProductSEOSelectScalar = {
  id?: boolean
  productId?: boolean
  metaTitle?: boolean
  metaDescription?: boolean
  metaKeyword?: boolean
}

export type ProductSEOOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "metaTitle" | "metaDescription" | "metaKeyword", ExtArgs["result"]["productSEO"]>
export type ProductSEOInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductSEOIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductSEOIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductSEOPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductSEO"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    metaTitle: string | null
    metaDescription: string | null
    metaKeyword: string | null
  }, ExtArgs["result"]["productSEO"]>
  composites: {}
}

export type ProductSEOGetPayload<S extends boolean | null | undefined | ProductSEODefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload, S>

export type ProductSEOCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductSEOFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductSEOCountAggregateInputType | true
  }

export interface ProductSEODelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductSEO'], meta: { name: 'ProductSEO' } }
  /**
   * Find zero or one ProductSEO that matches the filter.
   * @param {ProductSEOFindUniqueArgs} args - Arguments to find a ProductSEO
   * @example
   * // Get one ProductSEO
   * const productSEO = await prisma.productSEO.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductSEOFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductSEOFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductSEO that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductSEOFindUniqueOrThrowArgs} args - Arguments to find a ProductSEO
   * @example
   * // Get one ProductSEO
   * const productSEO = await prisma.productSEO.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductSEOFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductSEOFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductSEO that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOFindFirstArgs} args - Arguments to find a ProductSEO
   * @example
   * // Get one ProductSEO
   * const productSEO = await prisma.productSEO.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductSEOFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductSEOFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductSEO that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOFindFirstOrThrowArgs} args - Arguments to find a ProductSEO
   * @example
   * // Get one ProductSEO
   * const productSEO = await prisma.productSEO.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductSEOFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductSEOFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductSEOS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductSEOS
   * const productSEOS = await prisma.productSEO.findMany()
   * 
   * // Get first 10 ProductSEOS
   * const productSEOS = await prisma.productSEO.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productSEOWithIdOnly = await prisma.productSEO.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductSEOFindManyArgs>(args?: Prisma.SelectSubset<T, ProductSEOFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductSEO.
   * @param {ProductSEOCreateArgs} args - Arguments to create a ProductSEO.
   * @example
   * // Create one ProductSEO
   * const ProductSEO = await prisma.productSEO.create({
   *   data: {
   *     // ... data to create a ProductSEO
   *   }
   * })
   * 
   */
  create<T extends ProductSEOCreateArgs>(args: Prisma.SelectSubset<T, ProductSEOCreateArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductSEOS.
   * @param {ProductSEOCreateManyArgs} args - Arguments to create many ProductSEOS.
   * @example
   * // Create many ProductSEOS
   * const productSEO = await prisma.productSEO.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductSEOCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductSEOCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductSEOS and returns the data saved in the database.
   * @param {ProductSEOCreateManyAndReturnArgs} args - Arguments to create many ProductSEOS.
   * @example
   * // Create many ProductSEOS
   * const productSEO = await prisma.productSEO.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductSEOS and only return the `id`
   * const productSEOWithIdOnly = await prisma.productSEO.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductSEOCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductSEOCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductSEO.
   * @param {ProductSEODeleteArgs} args - Arguments to delete one ProductSEO.
   * @example
   * // Delete one ProductSEO
   * const ProductSEO = await prisma.productSEO.delete({
   *   where: {
   *     // ... filter to delete one ProductSEO
   *   }
   * })
   * 
   */
  delete<T extends ProductSEODeleteArgs>(args: Prisma.SelectSubset<T, ProductSEODeleteArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductSEO.
   * @param {ProductSEOUpdateArgs} args - Arguments to update one ProductSEO.
   * @example
   * // Update one ProductSEO
   * const productSEO = await prisma.productSEO.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductSEOUpdateArgs>(args: Prisma.SelectSubset<T, ProductSEOUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductSEOS.
   * @param {ProductSEODeleteManyArgs} args - Arguments to filter ProductSEOS to delete.
   * @example
   * // Delete a few ProductSEOS
   * const { count } = await prisma.productSEO.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductSEODeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductSEODeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductSEOS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductSEOS
   * const productSEO = await prisma.productSEO.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductSEOUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductSEOUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductSEOS and returns the data updated in the database.
   * @param {ProductSEOUpdateManyAndReturnArgs} args - Arguments to update many ProductSEOS.
   * @example
   * // Update many ProductSEOS
   * const productSEO = await prisma.productSEO.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductSEOS and only return the `id`
   * const productSEOWithIdOnly = await prisma.productSEO.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductSEOUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductSEOUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductSEO.
   * @param {ProductSEOUpsertArgs} args - Arguments to update or create a ProductSEO.
   * @example
   * // Update or create a ProductSEO
   * const productSEO = await prisma.productSEO.upsert({
   *   create: {
   *     // ... data to create a ProductSEO
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductSEO we want to update
   *   }
   * })
   */
  upsert<T extends ProductSEOUpsertArgs>(args: Prisma.SelectSubset<T, ProductSEOUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductSEOClient<runtime.Types.Result.GetResult<Prisma.$ProductSEOPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductSEOS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOCountArgs} args - Arguments to filter ProductSEOS to count.
   * @example
   * // Count the number of ProductSEOS
   * const count = await prisma.productSEO.count({
   *   where: {
   *     // ... the filter for the ProductSEOS we want to count
   *   }
   * })
  **/
  count<T extends ProductSEOCountArgs>(
    args?: Prisma.Subset<T, ProductSEOCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductSEOCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductSEO.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductSEOAggregateArgs>(args: Prisma.Subset<T, ProductSEOAggregateArgs>): Prisma.PrismaPromise<GetProductSEOAggregateType<T>>

  /**
   * Group by ProductSEO.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductSEOGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductSEOGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductSEOGroupByArgs['orderBy'] }
      : { orderBy?: ProductSEOGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductSEOGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductSEOGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductSEO model
 */
readonly fields: ProductSEOFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductSEO.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductSEOClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductSEO model
 */
export interface ProductSEOFieldRefs {
  readonly id: Prisma.FieldRef<"ProductSEO", 'String'>
  readonly productId: Prisma.FieldRef<"ProductSEO", 'String'>
  readonly metaTitle: Prisma.FieldRef<"ProductSEO", 'String'>
  readonly metaDescription: Prisma.FieldRef<"ProductSEO", 'String'>
  readonly metaKeyword: Prisma.FieldRef<"ProductSEO", 'String'>
}
    

// Custom InputTypes
/**
 * ProductSEO findUnique
 */
export type ProductSEOFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * Filter, which ProductSEO to fetch.
   */
  where: Prisma.ProductSEOWhereUniqueInput
}

/**
 * ProductSEO findUniqueOrThrow
 */
export type ProductSEOFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * Filter, which ProductSEO to fetch.
   */
  where: Prisma.ProductSEOWhereUniqueInput
}

/**
 * ProductSEO findFirst
 */
export type ProductSEOFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * Filter, which ProductSEO to fetch.
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductSEOS to fetch.
   */
  orderBy?: Prisma.ProductSEOOrderByWithRelationInput | Prisma.ProductSEOOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductSEOS.
   */
  cursor?: Prisma.ProductSEOWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductSEOS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductSEOS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductSEOS.
   */
  distinct?: Prisma.ProductSEOScalarFieldEnum | Prisma.ProductSEOScalarFieldEnum[]
}

/**
 * ProductSEO findFirstOrThrow
 */
export type ProductSEOFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * Filter, which ProductSEO to fetch.
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductSEOS to fetch.
   */
  orderBy?: Prisma.ProductSEOOrderByWithRelationInput | Prisma.ProductSEOOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductSEOS.
   */
  cursor?: Prisma.ProductSEOWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductSEOS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductSEOS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductSEOS.
   */
  distinct?: Prisma.ProductSEOScalarFieldEnum | Prisma.ProductSEOScalarFieldEnum[]
}

/**
 * ProductSEO findMany
 */
export type ProductSEOFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * Filter, which ProductSEOS to fetch.
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductSEOS to fetch.
   */
  orderBy?: Prisma.ProductSEOOrderByWithRelationInput | Prisma.ProductSEOOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductSEOS.
   */
  cursor?: Prisma.ProductSEOWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductSEOS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductSEOS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductSEOS.
   */
  distinct?: Prisma.ProductSEOScalarFieldEnum | Prisma.ProductSEOScalarFieldEnum[]
}

/**
 * ProductSEO create
 */
export type ProductSEOCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductSEO.
   */
  data: Prisma.XOR<Prisma.ProductSEOCreateInput, Prisma.ProductSEOUncheckedCreateInput>
}

/**
 * ProductSEO createMany
 */
export type ProductSEOCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductSEOS.
   */
  data: Prisma.ProductSEOCreateManyInput | Prisma.ProductSEOCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductSEO createManyAndReturn
 */
export type ProductSEOCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * The data used to create many ProductSEOS.
   */
  data: Prisma.ProductSEOCreateManyInput | Prisma.ProductSEOCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductSEO update
 */
export type ProductSEOUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductSEO.
   */
  data: Prisma.XOR<Prisma.ProductSEOUpdateInput, Prisma.ProductSEOUncheckedUpdateInput>
  /**
   * Choose, which ProductSEO to update.
   */
  where: Prisma.ProductSEOWhereUniqueInput
}

/**
 * ProductSEO updateMany
 */
export type ProductSEOUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductSEOS.
   */
  data: Prisma.XOR<Prisma.ProductSEOUpdateManyMutationInput, Prisma.ProductSEOUncheckedUpdateManyInput>
  /**
   * Filter which ProductSEOS to update
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * Limit how many ProductSEOS to update.
   */
  limit?: number
}

/**
 * ProductSEO updateManyAndReturn
 */
export type ProductSEOUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * The data used to update ProductSEOS.
   */
  data: Prisma.XOR<Prisma.ProductSEOUpdateManyMutationInput, Prisma.ProductSEOUncheckedUpdateManyInput>
  /**
   * Filter which ProductSEOS to update
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * Limit how many ProductSEOS to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductSEO upsert
 */
export type ProductSEOUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductSEO to update in case it exists.
   */
  where: Prisma.ProductSEOWhereUniqueInput
  /**
   * In case the ProductSEO found by the `where` argument doesn't exist, create a new ProductSEO with this data.
   */
  create: Prisma.XOR<Prisma.ProductSEOCreateInput, Prisma.ProductSEOUncheckedCreateInput>
  /**
   * In case the ProductSEO was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductSEOUpdateInput, Prisma.ProductSEOUncheckedUpdateInput>
}

/**
 * ProductSEO delete
 */
export type ProductSEODeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
  /**
   * Filter which ProductSEO to delete.
   */
  where: Prisma.ProductSEOWhereUniqueInput
}

/**
 * ProductSEO deleteMany
 */
export type ProductSEODeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductSEOS to delete
   */
  where?: Prisma.ProductSEOWhereInput
  /**
   * Limit how many ProductSEOS to delete.
   */
  limit?: number
}

/**
 * ProductSEO without action
 */
export type ProductSEODefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductSEO
   */
  select?: Prisma.ProductSEOSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductSEO
   */
  omit?: Prisma.ProductSEOOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductSEOInclude<ExtArgs> | null
}
