
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductUsage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ProductUsage
 * 
 */
export type ProductUsageModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductUsagePayload>

export type AggregateProductUsage = {
  _count: ProductUsageCountAggregateOutputType | null
  _avg: ProductUsageAvgAggregateOutputType | null
  _sum: ProductUsageSumAggregateOutputType | null
  _min: ProductUsageMinAggregateOutputType | null
  _max: ProductUsageMaxAggregateOutputType | null
}

export type ProductUsageAvgAggregateOutputType = {
  stepNumber: number | null
}

export type ProductUsageSumAggregateOutputType = {
  stepNumber: number | null
}

export type ProductUsageMinAggregateOutputType = {
  id: string | null
  productId: string | null
  stepNumber: number | null
  content: string | null
}

export type ProductUsageMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  stepNumber: number | null
  content: string | null
}

export type ProductUsageCountAggregateOutputType = {
  id: number
  productId: number
  stepNumber: number
  content: number
  _all: number
}


export type ProductUsageAvgAggregateInputType = {
  stepNumber?: true
}

export type ProductUsageSumAggregateInputType = {
  stepNumber?: true
}

export type ProductUsageMinAggregateInputType = {
  id?: true
  productId?: true
  stepNumber?: true
  content?: true
}

export type ProductUsageMaxAggregateInputType = {
  id?: true
  productId?: true
  stepNumber?: true
  content?: true
}

export type ProductUsageCountAggregateInputType = {
  id?: true
  productId?: true
  stepNumber?: true
  content?: true
  _all?: true
}

export type ProductUsageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductUsage to aggregate.
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductUsages to fetch.
   */
  orderBy?: Prisma.ProductUsageOrderByWithRelationInput | Prisma.ProductUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductUsages
  **/
  _count?: true | ProductUsageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProductUsageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProductUsageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductUsageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductUsageMaxAggregateInputType
}

export type GetProductUsageAggregateType<T extends ProductUsageAggregateArgs> = {
      [P in keyof T & keyof AggregateProductUsage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductUsage[P]>
    : Prisma.GetScalarType<T[P], AggregateProductUsage[P]>
}




export type ProductUsageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductUsageWhereInput
  orderBy?: Prisma.ProductUsageOrderByWithAggregationInput | Prisma.ProductUsageOrderByWithAggregationInput[]
  by: Prisma.ProductUsageScalarFieldEnum[] | Prisma.ProductUsageScalarFieldEnum
  having?: Prisma.ProductUsageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductUsageCountAggregateInputType | true
  _avg?: ProductUsageAvgAggregateInputType
  _sum?: ProductUsageSumAggregateInputType
  _min?: ProductUsageMinAggregateInputType
  _max?: ProductUsageMaxAggregateInputType
}

export type ProductUsageGroupByOutputType = {
  id: string
  productId: string
  stepNumber: number
  content: string
  _count: ProductUsageCountAggregateOutputType | null
  _avg: ProductUsageAvgAggregateOutputType | null
  _sum: ProductUsageSumAggregateOutputType | null
  _min: ProductUsageMinAggregateOutputType | null
  _max: ProductUsageMaxAggregateOutputType | null
}

export type GetProductUsageGroupByPayload<T extends ProductUsageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductUsageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductUsageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductUsageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductUsageGroupByOutputType[P]>
      }
    >
  >



export type ProductUsageWhereInput = {
  AND?: Prisma.ProductUsageWhereInput | Prisma.ProductUsageWhereInput[]
  OR?: Prisma.ProductUsageWhereInput[]
  NOT?: Prisma.ProductUsageWhereInput | Prisma.ProductUsageWhereInput[]
  id?: Prisma.StringFilter<"ProductUsage"> | string
  productId?: Prisma.StringFilter<"ProductUsage"> | string
  stepNumber?: Prisma.IntFilter<"ProductUsage"> | number
  content?: Prisma.StringFilter<"ProductUsage"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type ProductUsageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  stepNumber?: Prisma.SortOrder
  content?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
}

export type ProductUsageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProductUsageWhereInput | Prisma.ProductUsageWhereInput[]
  OR?: Prisma.ProductUsageWhereInput[]
  NOT?: Prisma.ProductUsageWhereInput | Prisma.ProductUsageWhereInput[]
  productId?: Prisma.StringFilter<"ProductUsage"> | string
  stepNumber?: Prisma.IntFilter<"ProductUsage"> | number
  content?: Prisma.StringFilter<"ProductUsage"> | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type ProductUsageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  stepNumber?: Prisma.SortOrder
  content?: Prisma.SortOrder
  _count?: Prisma.ProductUsageCountOrderByAggregateInput
  _avg?: Prisma.ProductUsageAvgOrderByAggregateInput
  _max?: Prisma.ProductUsageMaxOrderByAggregateInput
  _min?: Prisma.ProductUsageMinOrderByAggregateInput
  _sum?: Prisma.ProductUsageSumOrderByAggregateInput
}

export type ProductUsageScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductUsageScalarWhereWithAggregatesInput | Prisma.ProductUsageScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductUsageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductUsageScalarWhereWithAggregatesInput | Prisma.ProductUsageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductUsage"> | string
  productId?: Prisma.StringWithAggregatesFilter<"ProductUsage"> | string
  stepNumber?: Prisma.IntWithAggregatesFilter<"ProductUsage"> | number
  content?: Prisma.StringWithAggregatesFilter<"ProductUsage"> | string
}

export type ProductUsageCreateInput = {
  id?: string
  stepNumber: number
  content: string
  product: Prisma.ProductCreateNestedOneWithoutHowToUseInput
}

export type ProductUsageUncheckedCreateInput = {
  id?: string
  productId: string
  stepNumber: number
  content: string
}

export type ProductUsageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  product?: Prisma.ProductUpdateOneRequiredWithoutHowToUseNestedInput
}

export type ProductUsageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductUsageCreateManyInput = {
  id?: string
  productId: string
  stepNumber: number
  content: string
}

export type ProductUsageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductUsageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductUsageListRelationFilter = {
  every?: Prisma.ProductUsageWhereInput
  some?: Prisma.ProductUsageWhereInput
  none?: Prisma.ProductUsageWhereInput
}

export type ProductUsageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductUsageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  stepNumber?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type ProductUsageAvgOrderByAggregateInput = {
  stepNumber?: Prisma.SortOrder
}

export type ProductUsageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  stepNumber?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type ProductUsageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  stepNumber?: Prisma.SortOrder
  content?: Prisma.SortOrder
}

export type ProductUsageSumOrderByAggregateInput = {
  stepNumber?: Prisma.SortOrder
}

export type ProductUsageCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductUsageCreateWithoutProductInput, Prisma.ProductUsageUncheckedCreateWithoutProductInput> | Prisma.ProductUsageCreateWithoutProductInput[] | Prisma.ProductUsageUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductUsageCreateOrConnectWithoutProductInput | Prisma.ProductUsageCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductUsageCreateManyProductInputEnvelope
  connect?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
}

export type ProductUsageUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductUsageCreateWithoutProductInput, Prisma.ProductUsageUncheckedCreateWithoutProductInput> | Prisma.ProductUsageCreateWithoutProductInput[] | Prisma.ProductUsageUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductUsageCreateOrConnectWithoutProductInput | Prisma.ProductUsageCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductUsageCreateManyProductInputEnvelope
  connect?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
}

export type ProductUsageUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductUsageCreateWithoutProductInput, Prisma.ProductUsageUncheckedCreateWithoutProductInput> | Prisma.ProductUsageCreateWithoutProductInput[] | Prisma.ProductUsageUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductUsageCreateOrConnectWithoutProductInput | Prisma.ProductUsageCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductUsageUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductUsageUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductUsageCreateManyProductInputEnvelope
  set?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  disconnect?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  delete?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  connect?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  update?: Prisma.ProductUsageUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductUsageUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductUsageUpdateManyWithWhereWithoutProductInput | Prisma.ProductUsageUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductUsageScalarWhereInput | Prisma.ProductUsageScalarWhereInput[]
}

export type ProductUsageUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductUsageCreateWithoutProductInput, Prisma.ProductUsageUncheckedCreateWithoutProductInput> | Prisma.ProductUsageCreateWithoutProductInput[] | Prisma.ProductUsageUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductUsageCreateOrConnectWithoutProductInput | Prisma.ProductUsageCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductUsageUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductUsageUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductUsageCreateManyProductInputEnvelope
  set?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  disconnect?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  delete?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  connect?: Prisma.ProductUsageWhereUniqueInput | Prisma.ProductUsageWhereUniqueInput[]
  update?: Prisma.ProductUsageUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductUsageUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductUsageUpdateManyWithWhereWithoutProductInput | Prisma.ProductUsageUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductUsageScalarWhereInput | Prisma.ProductUsageScalarWhereInput[]
}

export type ProductUsageCreateWithoutProductInput = {
  id?: string
  stepNumber: number
  content: string
}

export type ProductUsageUncheckedCreateWithoutProductInput = {
  id?: string
  stepNumber: number
  content: string
}

export type ProductUsageCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductUsageWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductUsageCreateWithoutProductInput, Prisma.ProductUsageUncheckedCreateWithoutProductInput>
}

export type ProductUsageCreateManyProductInputEnvelope = {
  data: Prisma.ProductUsageCreateManyProductInput | Prisma.ProductUsageCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type ProductUsageUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductUsageWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductUsageUpdateWithoutProductInput, Prisma.ProductUsageUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductUsageCreateWithoutProductInput, Prisma.ProductUsageUncheckedCreateWithoutProductInput>
}

export type ProductUsageUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductUsageWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductUsageUpdateWithoutProductInput, Prisma.ProductUsageUncheckedUpdateWithoutProductInput>
}

export type ProductUsageUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductUsageScalarWhereInput
  data: Prisma.XOR<Prisma.ProductUsageUpdateManyMutationInput, Prisma.ProductUsageUncheckedUpdateManyWithoutProductInput>
}

export type ProductUsageScalarWhereInput = {
  AND?: Prisma.ProductUsageScalarWhereInput | Prisma.ProductUsageScalarWhereInput[]
  OR?: Prisma.ProductUsageScalarWhereInput[]
  NOT?: Prisma.ProductUsageScalarWhereInput | Prisma.ProductUsageScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductUsage"> | string
  productId?: Prisma.StringFilter<"ProductUsage"> | string
  stepNumber?: Prisma.IntFilter<"ProductUsage"> | number
  content?: Prisma.StringFilter<"ProductUsage"> | string
}

export type ProductUsageCreateManyProductInput = {
  id?: string
  stepNumber: number
  content: string
}

export type ProductUsageUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductUsageUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProductUsageUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepNumber?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ProductUsageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  stepNumber?: boolean
  content?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productUsage"]>

export type ProductUsageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  stepNumber?: boolean
  content?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productUsage"]>

export type ProductUsageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  stepNumber?: boolean
  content?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productUsage"]>

export type ProductUsageSelectScalar = {
  id?: boolean
  productId?: boolean
  stepNumber?: boolean
  content?: boolean
}

export type ProductUsageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "stepNumber" | "content", ExtArgs["result"]["productUsage"]>
export type ProductUsageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductUsageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type ProductUsageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $ProductUsagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductUsage"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    stepNumber: number
    content: string
  }, ExtArgs["result"]["productUsage"]>
  composites: {}
}

export type ProductUsageGetPayload<S extends boolean | null | undefined | ProductUsageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload, S>

export type ProductUsageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductUsageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductUsageCountAggregateInputType | true
  }

export interface ProductUsageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductUsage'], meta: { name: 'ProductUsage' } }
  /**
   * Find zero or one ProductUsage that matches the filter.
   * @param {ProductUsageFindUniqueArgs} args - Arguments to find a ProductUsage
   * @example
   * // Get one ProductUsage
   * const productUsage = await prisma.productUsage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductUsageFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductUsageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductUsage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductUsageFindUniqueOrThrowArgs} args - Arguments to find a ProductUsage
   * @example
   * // Get one ProductUsage
   * const productUsage = await prisma.productUsage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductUsageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductUsageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductUsage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageFindFirstArgs} args - Arguments to find a ProductUsage
   * @example
   * // Get one ProductUsage
   * const productUsage = await prisma.productUsage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductUsageFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductUsageFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductUsage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageFindFirstOrThrowArgs} args - Arguments to find a ProductUsage
   * @example
   * // Get one ProductUsage
   * const productUsage = await prisma.productUsage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductUsageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductUsageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductUsages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductUsages
   * const productUsages = await prisma.productUsage.findMany()
   * 
   * // Get first 10 ProductUsages
   * const productUsages = await prisma.productUsage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productUsageWithIdOnly = await prisma.productUsage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductUsageFindManyArgs>(args?: Prisma.SelectSubset<T, ProductUsageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductUsage.
   * @param {ProductUsageCreateArgs} args - Arguments to create a ProductUsage.
   * @example
   * // Create one ProductUsage
   * const ProductUsage = await prisma.productUsage.create({
   *   data: {
   *     // ... data to create a ProductUsage
   *   }
   * })
   * 
   */
  create<T extends ProductUsageCreateArgs>(args: Prisma.SelectSubset<T, ProductUsageCreateArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductUsages.
   * @param {ProductUsageCreateManyArgs} args - Arguments to create many ProductUsages.
   * @example
   * // Create many ProductUsages
   * const productUsage = await prisma.productUsage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductUsageCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductUsageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductUsages and returns the data saved in the database.
   * @param {ProductUsageCreateManyAndReturnArgs} args - Arguments to create many ProductUsages.
   * @example
   * // Create many ProductUsages
   * const productUsage = await prisma.productUsage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductUsages and only return the `id`
   * const productUsageWithIdOnly = await prisma.productUsage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductUsageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductUsageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductUsage.
   * @param {ProductUsageDeleteArgs} args - Arguments to delete one ProductUsage.
   * @example
   * // Delete one ProductUsage
   * const ProductUsage = await prisma.productUsage.delete({
   *   where: {
   *     // ... filter to delete one ProductUsage
   *   }
   * })
   * 
   */
  delete<T extends ProductUsageDeleteArgs>(args: Prisma.SelectSubset<T, ProductUsageDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductUsage.
   * @param {ProductUsageUpdateArgs} args - Arguments to update one ProductUsage.
   * @example
   * // Update one ProductUsage
   * const productUsage = await prisma.productUsage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductUsageUpdateArgs>(args: Prisma.SelectSubset<T, ProductUsageUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductUsages.
   * @param {ProductUsageDeleteManyArgs} args - Arguments to filter ProductUsages to delete.
   * @example
   * // Delete a few ProductUsages
   * const { count } = await prisma.productUsage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductUsageDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductUsageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductUsages
   * const productUsage = await prisma.productUsage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductUsageUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductUsageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductUsages and returns the data updated in the database.
   * @param {ProductUsageUpdateManyAndReturnArgs} args - Arguments to update many ProductUsages.
   * @example
   * // Update many ProductUsages
   * const productUsage = await prisma.productUsage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductUsages and only return the `id`
   * const productUsageWithIdOnly = await prisma.productUsage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductUsageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductUsageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductUsage.
   * @param {ProductUsageUpsertArgs} args - Arguments to update or create a ProductUsage.
   * @example
   * // Update or create a ProductUsage
   * const productUsage = await prisma.productUsage.upsert({
   *   create: {
   *     // ... data to create a ProductUsage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductUsage we want to update
   *   }
   * })
   */
  upsert<T extends ProductUsageUpsertArgs>(args: Prisma.SelectSubset<T, ProductUsageUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductUsageClient<runtime.Types.Result.GetResult<Prisma.$ProductUsagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageCountArgs} args - Arguments to filter ProductUsages to count.
   * @example
   * // Count the number of ProductUsages
   * const count = await prisma.productUsage.count({
   *   where: {
   *     // ... the filter for the ProductUsages we want to count
   *   }
   * })
  **/
  count<T extends ProductUsageCountArgs>(
    args?: Prisma.Subset<T, ProductUsageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductUsageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductUsageAggregateArgs>(args: Prisma.Subset<T, ProductUsageAggregateArgs>): Prisma.PrismaPromise<GetProductUsageAggregateType<T>>

  /**
   * Group by ProductUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductUsageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductUsageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductUsageGroupByArgs['orderBy'] }
      : { orderBy?: ProductUsageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductUsageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductUsageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductUsage model
 */
readonly fields: ProductUsageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductUsage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductUsageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductUsage model
 */
export interface ProductUsageFieldRefs {
  readonly id: Prisma.FieldRef<"ProductUsage", 'String'>
  readonly productId: Prisma.FieldRef<"ProductUsage", 'String'>
  readonly stepNumber: Prisma.FieldRef<"ProductUsage", 'Int'>
  readonly content: Prisma.FieldRef<"ProductUsage", 'String'>
}
    

// Custom InputTypes
/**
 * ProductUsage findUnique
 */
export type ProductUsageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * Filter, which ProductUsage to fetch.
   */
  where: Prisma.ProductUsageWhereUniqueInput
}

/**
 * ProductUsage findUniqueOrThrow
 */
export type ProductUsageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * Filter, which ProductUsage to fetch.
   */
  where: Prisma.ProductUsageWhereUniqueInput
}

/**
 * ProductUsage findFirst
 */
export type ProductUsageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * Filter, which ProductUsage to fetch.
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductUsages to fetch.
   */
  orderBy?: Prisma.ProductUsageOrderByWithRelationInput | Prisma.ProductUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductUsages.
   */
  cursor?: Prisma.ProductUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductUsages.
   */
  distinct?: Prisma.ProductUsageScalarFieldEnum | Prisma.ProductUsageScalarFieldEnum[]
}

/**
 * ProductUsage findFirstOrThrow
 */
export type ProductUsageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * Filter, which ProductUsage to fetch.
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductUsages to fetch.
   */
  orderBy?: Prisma.ProductUsageOrderByWithRelationInput | Prisma.ProductUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductUsages.
   */
  cursor?: Prisma.ProductUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductUsages.
   */
  distinct?: Prisma.ProductUsageScalarFieldEnum | Prisma.ProductUsageScalarFieldEnum[]
}

/**
 * ProductUsage findMany
 */
export type ProductUsageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * Filter, which ProductUsages to fetch.
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductUsages to fetch.
   */
  orderBy?: Prisma.ProductUsageOrderByWithRelationInput | Prisma.ProductUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductUsages.
   */
  cursor?: Prisma.ProductUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductUsages.
   */
  distinct?: Prisma.ProductUsageScalarFieldEnum | Prisma.ProductUsageScalarFieldEnum[]
}

/**
 * ProductUsage create
 */
export type ProductUsageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductUsage.
   */
  data: Prisma.XOR<Prisma.ProductUsageCreateInput, Prisma.ProductUsageUncheckedCreateInput>
}

/**
 * ProductUsage createMany
 */
export type ProductUsageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductUsages.
   */
  data: Prisma.ProductUsageCreateManyInput | Prisma.ProductUsageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductUsage createManyAndReturn
 */
export type ProductUsageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * The data used to create many ProductUsages.
   */
  data: Prisma.ProductUsageCreateManyInput | Prisma.ProductUsageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductUsage update
 */
export type ProductUsageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductUsage.
   */
  data: Prisma.XOR<Prisma.ProductUsageUpdateInput, Prisma.ProductUsageUncheckedUpdateInput>
  /**
   * Choose, which ProductUsage to update.
   */
  where: Prisma.ProductUsageWhereUniqueInput
}

/**
 * ProductUsage updateMany
 */
export type ProductUsageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductUsages.
   */
  data: Prisma.XOR<Prisma.ProductUsageUpdateManyMutationInput, Prisma.ProductUsageUncheckedUpdateManyInput>
  /**
   * Filter which ProductUsages to update
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * Limit how many ProductUsages to update.
   */
  limit?: number
}

/**
 * ProductUsage updateManyAndReturn
 */
export type ProductUsageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * The data used to update ProductUsages.
   */
  data: Prisma.XOR<Prisma.ProductUsageUpdateManyMutationInput, Prisma.ProductUsageUncheckedUpdateManyInput>
  /**
   * Filter which ProductUsages to update
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * Limit how many ProductUsages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductUsage upsert
 */
export type ProductUsageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductUsage to update in case it exists.
   */
  where: Prisma.ProductUsageWhereUniqueInput
  /**
   * In case the ProductUsage found by the `where` argument doesn't exist, create a new ProductUsage with this data.
   */
  create: Prisma.XOR<Prisma.ProductUsageCreateInput, Prisma.ProductUsageUncheckedCreateInput>
  /**
   * In case the ProductUsage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductUsageUpdateInput, Prisma.ProductUsageUncheckedUpdateInput>
}

/**
 * ProductUsage delete
 */
export type ProductUsageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
  /**
   * Filter which ProductUsage to delete.
   */
  where: Prisma.ProductUsageWhereUniqueInput
}

/**
 * ProductUsage deleteMany
 */
export type ProductUsageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductUsages to delete
   */
  where?: Prisma.ProductUsageWhereInput
  /**
   * Limit how many ProductUsages to delete.
   */
  limit?: number
}

/**
 * ProductUsage without action
 */
export type ProductUsageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductUsage
   */
  select?: Prisma.ProductUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductUsage
   */
  omit?: Prisma.ProductUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductUsageInclude<ExtArgs> | null
}
