
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Clients
 * const clients = await prisma.client.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Client
 * 
 */
export type Client = Prisma.ClientModel
/**
 * Model Banner
 * 
 */
export type Banner = Prisma.BannerModel
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model CompanyInfo
 * 
 */
export type CompanyInfo = Prisma.CompanyInfoModel
/**
 * Model Footer
 * 
 */
export type Footer = Prisma.FooterModel
/**
 * Model FooterSocial
 * 
 */
export type FooterSocial = Prisma.FooterSocialModel
/**
 * Model FooterSection
 * 
 */
export type FooterSection = Prisma.FooterSectionModel
/**
 * Model FooterLink
 * 
 */
export type FooterLink = Prisma.FooterLinkModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model Ingredient
 * 
 */
export type Ingredient = Prisma.IngredientModel
/**
 * Model ProductUsage
 * 
 */
export type ProductUsage = Prisma.ProductUsageModel
/**
 * Model ProductBenefit
 * 
 */
export type ProductBenefit = Prisma.ProductBenefitModel
/**
 * Model ProductSEO
 * 
 */
export type ProductSEO = Prisma.ProductSEOModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
