
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ProductStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  ARCHIVED: 'ARCHIVED'
} as const

export type ProductStatus = (typeof ProductStatus)[keyof typeof ProductStatus]


export const Role = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER'
} as const

export type Role = (typeof Role)[keyof typeof Role]
