
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Client.js'
export type * from './models/Banner.js'
export type * from './models/Category.js'
export type * from './models/CompanyInfo.js'
export type * from './models/Footer.js'
export type * from './models/FooterSocial.js'
export type * from './models/FooterSection.js'
export type * from './models/FooterLink.js'
export type * from './models/User.js'
export type * from './commonInputTypes.js'